// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/unit/core/services/base/service_lifecycle_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jisu_fund_analyzer/src/core/services/base/i_unified_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeServiceHealthStatus_0 extends _i1.SmartFake
    implements _i2.ServiceHealthStatus {
  _FakeServiceHealthStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServiceStats_1 extends _i1.SmartFake implements _i2.ServiceStats {
  _FakeServiceStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IUnifiedService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUnifiedService extends _i1.Mock implements _i2.IUnifiedService {
  MockIUnifiedService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get serviceName => (super.noSuchMethod(
        Invocation.getter(#serviceName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#serviceName),
        ),
      ) as String);

  @override
  String get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#version),
        ),
      ) as String);

  @override
  List<String> get dependencies => (super.noSuchMethod(
        Invocation.getter(#dependencies),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i2.ServiceLifecycleState get lifecycleState => (super.noSuchMethod(
        Invocation.getter(#lifecycleState),
        returnValue: _i2.ServiceLifecycleState.uninitialized,
      ) as _i2.ServiceLifecycleState);

  @override
  _i4.Future<void> initialize(_i2.ServiceContainer? container) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [container],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.ServiceHealthStatus> checkHealth() => (super.noSuchMethod(
        Invocation.method(
          #checkHealth,
          [],
        ),
        returnValue: _i4.Future<_i2.ServiceHealthStatus>.value(
            _FakeServiceHealthStatus_0(
          this,
          Invocation.method(
            #checkHealth,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ServiceHealthStatus>);

  @override
  _i2.ServiceStats getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue: _FakeServiceStats_1(
          this,
          Invocation.method(
            #getStats,
            [],
          ),
        ),
      ) as _i2.ServiceStats);

  @override
  void setLifecycleState(_i2.ServiceLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #setLifecycleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ServiceContainer].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceContainer extends _i1.Mock implements _i2.ServiceContainer {
  MockServiceContainer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> registerService<T extends _i2.IUnifiedService>(T? service) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerService,
          [service],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  T getService<T extends _i2.IUnifiedService>() => (super.noSuchMethod(
        Invocation.method(
          #getService,
          [],
        ),
        returnValue: _i3.dummyValue<T>(
          this,
          Invocation.method(
            #getService,
            [],
          ),
        ),
      ) as T);

  @override
  bool isRegistered<T extends _i2.IUnifiedService>() => (super.noSuchMethod(
        Invocation.method(
          #isRegistered,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String> getRegisteredServiceNames() => (super.noSuchMethod(
        Invocation.method(
          #getRegisteredServiceNames,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i2.IUnifiedService? getServiceByName(String? serviceName) =>
      (super.noSuchMethod(Invocation.method(
        #getServiceByName,
        [serviceName],
      )) as _i2.IUnifiedService?);
}
