// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/unit/fund/widgets/story_1_6_folding_tool_panel_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bloc/bloc.dart' as _i6;
import 'package:jisu_fund_analyzer/src/core/state/tool_panel/tool_panel_cubit.dart'
    as _i2;
import 'package:jisu_fund_analyzer/src/features/fund/presentation/fund_exploration/presentation/cubit/fund_exploration_cubit.dart'
    as _i3;
import 'package:jisu_fund_analyzer/src/features/fund/shared/models/fund_ranking.dart'
    as _i7;
import 'package:jisu_fund_analyzer/src/features/fund/shared/services/fund_data_service.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeToolPanelState_0 extends _i1.SmartFake
    implements _i2.ToolPanelState {
  _FakeToolPanelState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFundExplorationState_1 extends _i1.SmartFake
    implements _i3.FundExplorationState {
  _FakeFundExplorationState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFundDataResult_2<T> extends _i1.SmartFake
    implements _i4.FundDataResult<T> {
  _FakeFundDataResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFundExplorationStatistics_3 extends _i1.SmartFake
    implements _i3.FundExplorationStatistics {
  _FakeFundExplorationStatistics_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ToolPanelCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockToolPanelCubit extends _i1.Mock implements _i2.ToolPanelCubit {
  MockToolPanelCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get expandedPanelCount => (super.noSuchMethod(
        Invocation.getter(#expandedPanelCount),
        returnValue: 0,
      ) as int);

  @override
  int get totalPanelCount => (super.noSuchMethod(
        Invocation.getter(#totalPanelCount),
        returnValue: 0,
      ) as int);

  @override
  bool get hasAnyPanelExpanded => (super.noSuchMethod(
        Invocation.getter(#hasAnyPanelExpanded),
        returnValue: false,
      ) as bool);

  @override
  bool get areAllPanelsExpanded => (super.noSuchMethod(
        Invocation.getter(#areAllPanelsExpanded),
        returnValue: false,
      ) as bool);

  @override
  _i2.ToolPanelState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeToolPanelState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.ToolPanelState);

  @override
  _i5.Stream<_i2.ToolPanelState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.ToolPanelState>.empty(),
      ) as _i5.Stream<_i2.ToolPanelState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadPanelStates() => (super.noSuchMethod(
        Invocation.method(
          #loadPanelStates,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setPanelExpanded(
    String? panelId,
    bool? isExpanded,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPanelExpanded,
          [
            panelId,
            isExpanded,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateMultiplePanelStates(Map<String, bool>? states) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMultiplePanelStates,
          [states],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> expandAllPanels() => (super.noSuchMethod(
        Invocation.method(
          #expandAllPanels,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> collapseAllPanels() => (super.noSuchMethod(
        Invocation.method(
          #collapseAllPanels,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetPanelStates() => (super.noSuchMethod(
        Invocation.method(
          #resetPanelStates,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> togglePanelExpanded(String? panelId) => (super.noSuchMethod(
        Invocation.method(
          #togglePanelExpanded,
          [panelId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i6.Change<_i2.ToolPanelState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.ToolPanelState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [FundExplorationCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockFundExplorationCubit extends _i1.Mock
    implements _i3.FundExplorationCubit {
  MockFundExplorationCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.FundRanking> get currentData => (super.noSuchMethod(
        Invocation.getter(#currentData),
        returnValue: <_i7.FundRanking>[],
      ) as List<_i7.FundRanking>);

  @override
  _i3.FundExplorationState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeFundExplorationState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.FundExplorationState);

  @override
  _i5.Stream<_i3.FundExplorationState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.FundExplorationState>.empty(),
      ) as _i5.Stream<_i3.FundExplorationState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadFundRankings({
    String? symbol = r'',
    bool? forceRefresh = false,
    int? maxRetries = 3,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFundRankings,
          [],
          {
            #symbol: symbol,
            #forceRefresh: forceRefresh,
            #maxRetries: maxRetries,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void searchFunds(String? query) => super.noSuchMethod(
        Invocation.method(
          #searchFunds,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getSearchSuggestions(String? query) => (super.noSuchMethod(
        Invocation.method(
          #getSearchSuggestions,
          [query],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> getRecentSearches() => (super.noSuchMethod(
        Invocation.method(
          #getRecentSearches,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void applyFilter({
    String? fundType,
    String? sortBy,
    String? sortOrder,
    double? minReturn,
    double? maxReturn,
    String? riskLevel,
    double? minFundSize,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #applyFilter,
          [],
          {
            #fundType: fundType,
            #sortBy: sortBy,
            #sortOrder: sortOrder,
            #minReturn: minReturn,
            #maxReturn: maxReturn,
            #riskLevel: riskLevel,
            #minFundSize: minFundSize,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void applyFilters({
    String? fundType,
    String? sortBy,
    String? minReturn,
    String? maxReturn,
    String? riskLevel,
    String? minFundSize,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #applyFilters,
          [],
          {
            #fundType: fundType,
            #sortBy: sortBy,
            #minReturn: minReturn,
            #maxReturn: maxReturn,
            #riskLevel: riskLevel,
            #minFundSize: minFundSize,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearComparison() => super.noSuchMethod(
        Invocation.method(
          #clearComparison,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addToComparison(_i7.FundRanking? fund) => super.noSuchMethod(
        Invocation.method(
          #addToComparison,
          [fund],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeFromComparison(String? fundCode) => super.noSuchMethod(
        Invocation.method(
          #removeFromComparison,
          [fundCode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleComparison(_i7.FundRanking? fund) => super.noSuchMethod(
        Invocation.method(
          #toggleComparison,
          [fund],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleFavorite(String? fundCode) => super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [fundCode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleComparisonByCode(String? fundCode) => super.noSuchMethod(
        Invocation.method(
          #toggleComparisonByCode,
          [fundCode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSearch() => super.noSuchMethod(
        Invocation.method(
          #clearSearch,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addToSearchHistory(String? query) => super.noSuchMethod(
        Invocation.method(
          #addToSearchHistory,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #updateSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void updateSortBy(String? sortBy) => super.noSuchMethod(
        Invocation.method(
          #updateSortBy,
          [sortBy],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetFilter() => super.noSuchMethod(
        Invocation.method(
          #resetFilter,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> refreshData() => (super.noSuchMethod(
        Invocation.method(
          #refreshData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> forceReloadData() => (super.noSuchMethod(
        Invocation.method(
          #forceReloadData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadMoreData() => (super.noSuchMethod(
        Invocation.method(
          #loadMoreData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void toggleFundExpanded(String? fundCode) => super.noSuchMethod(
        Invocation.method(
          #toggleFundExpanded,
          [fundCode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i4.FundDataResult<Map<String, dynamic>>> getFundDetail(
          String? fundCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFundDetail,
          [fundCode],
        ),
        returnValue: _i5.Future<_i4.FundDataResult<Map<String, dynamic>>>.value(
            _FakeFundDataResult_2<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getFundDetail,
            [fundCode],
          ),
        )),
      ) as _i5.Future<_i4.FundDataResult<Map<String, dynamic>>>);

  @override
  List<_i7.FundRanking> getHotFunds({int? limit = 10}) => (super.noSuchMethod(
        Invocation.method(
          #getHotFunds,
          [],
          {#limit: limit},
        ),
        returnValue: <_i7.FundRanking>[],
      ) as List<_i7.FundRanking>);

  @override
  List<_i7.FundRanking> getRecommendedFunds({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedFunds,
          [],
          {#limit: limit},
        ),
        returnValue: <_i7.FundRanking>[],
      ) as List<_i7.FundRanking>);

  @override
  _i3.FundExplorationStatistics getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _FakeFundExplorationStatistics_3(
          this,
          Invocation.method(
            #getStatistics,
            [],
          ),
        ),
      ) as _i3.FundExplorationStatistics);

  @override
  void clearSearchHistory() => super.noSuchMethod(
        Invocation.method(
          #clearSearchHistory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeFromSearchHistory(String? query) => super.noSuchMethod(
        Invocation.method(
          #removeFromSearchHistory,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loadMoneyFunds({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMoneyFunds,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void searchMoneyFunds(String? query) => super.noSuchMethod(
        Invocation.method(
          #searchMoneyFunds,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loadTopYieldMoneyFunds({int? count = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadTopYieldMoneyFunds,
          [],
          {#count: count},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void switchToMoneyFundsView() => super.noSuchMethod(
        Invocation.method(
          #switchToMoneyFundsView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void switchToRankingView() => super.noSuchMethod(
        Invocation.method(
          #switchToRankingView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void switchToSearchView() => super.noSuchMethod(
        Invocation.method(
          #switchToSearchView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void switchToComparisonView() => super.noSuchMethod(
        Invocation.method(
          #switchToComparisonView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void switchToHotView() => super.noSuchMethod(
        Invocation.method(
          #switchToHotView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearMoneyFundSearch() => super.noSuchMethod(
        Invocation.method(
          #clearMoneyFundSearch,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<Map<String, dynamic>?> getMoneyFundStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoneyFundStatistics,
          [],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void emit(_i3.FundExplorationState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i6.Change<_i3.FundExplorationState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
