// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/unit/fund/widgets/tool_panel_container_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bloc/bloc.dart' as _i4;
import 'package:jisu_fund_analyzer/src/core/state/tool_panel/tool_panel_cubit.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeToolPanelState_0 extends _i1.SmartFake
    implements _i2.ToolPanelState {
  _FakeToolPanelState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ToolPanelCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockToolPanelCubit extends _i1.Mock implements _i2.ToolPanelCubit {
  MockToolPanelCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get expandedPanelCount => (super.noSuchMethod(
        Invocation.getter(#expandedPanelCount),
        returnValue: 0,
      ) as int);

  @override
  int get totalPanelCount => (super.noSuchMethod(
        Invocation.getter(#totalPanelCount),
        returnValue: 0,
      ) as int);

  @override
  bool get hasAnyPanelExpanded => (super.noSuchMethod(
        Invocation.getter(#hasAnyPanelExpanded),
        returnValue: false,
      ) as bool);

  @override
  bool get areAllPanelsExpanded => (super.noSuchMethod(
        Invocation.getter(#areAllPanelsExpanded),
        returnValue: false,
      ) as bool);

  @override
  _i2.ToolPanelState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeToolPanelState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.ToolPanelState);

  @override
  _i3.Stream<_i2.ToolPanelState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i2.ToolPanelState>.empty(),
      ) as _i3.Stream<_i2.ToolPanelState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> loadPanelStates() => (super.noSuchMethod(
        Invocation.method(
          #loadPanelStates,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setPanelExpanded(
    String? panelId,
    bool? isExpanded,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPanelExpanded,
          [
            panelId,
            isExpanded,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateMultiplePanelStates(Map<String, bool>? states) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMultiplePanelStates,
          [states],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> expandAllPanels() => (super.noSuchMethod(
        Invocation.method(
          #expandAllPanels,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> collapseAllPanels() => (super.noSuchMethod(
        Invocation.method(
          #collapseAllPanels,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> resetPanelStates() => (super.noSuchMethod(
        Invocation.method(
          #resetPanelStates,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> togglePanelExpanded(String? panelId) => (super.noSuchMethod(
        Invocation.method(
          #togglePanelExpanded,
          [panelId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i4.Change<_i2.ToolPanelState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.ToolPanelState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
