// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/unit/core/services/performance/unified_performance_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jisu_fund_analyzer/src/core/services/base/i_unified_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ServiceContainer].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceContainer extends _i1.Mock implements _i2.ServiceContainer {
  MockServiceContainer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> registerService<T extends _i2.IUnifiedService>(T? service) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerService,
          [service],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  T getService<T extends _i2.IUnifiedService>() => (super.noSuchMethod(
        Invocation.method(
          #getService,
          [],
        ),
        returnValue: _i4.dummyValue<T>(
          this,
          Invocation.method(
            #getService,
            [],
          ),
        ),
      ) as T);

  @override
  bool isRegistered<T extends _i2.IUnifiedService>() => (super.noSuchMethod(
        Invocation.method(
          #isRegistered,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String> getRegisteredServiceNames() => (super.noSuchMethod(
        Invocation.method(
          #getRegisteredServiceNames,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i2.IUnifiedService? getServiceByName(String? serviceName) =>
      (super.noSuchMethod(Invocation.method(
        #getServiceByName,
        [serviceName],
      )) as _i2.IUnifiedService?);
}
