# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # 基础代码质量规则
    prefer_single_quotes: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
    unnecessary_new: true

    # 命名约定
    prefer_typing_uninitialized_variables: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    use_key_in_widget_constructors: true

    # 性能优化规则
    avoid_function_literals_in_foreach_calls: true
    avoid_slow_async_io: true
    prefer_spread_collections: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: false

    # 代码组织规则
    directives_ordering: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    type_init_formals: true

    # 错误预防规则
    avoid_type_to_string: true
    cast_nullable_to_non_nullable: false
    invalid_case_patterns: true
    literal_only_boolean_expressions: true
    no_default_cases: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true

    # Flutter特定规则
    avoid_unnecessary_containers: true
    sized_box_shrink_expand: true
    use_colored_box: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true
    use_if_null_to_convert_nulls_to_bools: true
    # 移除不存在的lint规则
    use_named_constants: true
    use_raw_strings: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true

    # 工具面板相关规则
    avoid_print: false  # 工具面板开发期间允许使用print调试

    # 文档规则
    public_member_api_docs: true
    package_names: true
    library_names: true

analyzer:
  exclude:
    - comprehensive_fix_backup/**
    - "comprehensive_fix_backup/*"
    - "**/comprehensive_fix_backup/**"
    - "*/comprehensive_fix_backup/*"
    - "**/*.g.dart"  # 排除生成的文件
    - "**/*.freezed.dart"  # 排除freezed生成文件
    - "**/build/**"  # 排除build目录
    - "**/generated/**"  # 排除生成的文件
    - "**/test/**/test_utils/**"  # 排除测试工具文件
    - "**/test/**/mocks/**"  # 排除mock文件

  # 错误和警告配置
  errors:
    # 将某些警告视为错误
    invalid_assignment: error
    invalid_override: error
    mixin_inherits_from_not_object: error
    mixin_of_non_class: error
    # 移除不存在的错误代码
    # subclass_of_abstract_class: error  # 此错误代码不存在
    # type_check_with_null_name: error   # 此错误代码不存在
    undefined_class: error
    undefined_getter: error
    undefined_identifier: error
    undefined_method: error
    undefined_operator: error
    undefined_setter: error
    undefined_super_member: error

  # 移除不支持的严格检查选项

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# 项目特定配置
#
# 工具面板开发相关说明：
# 1. use_key_in_widget_constructors: 确保所有Widget都有key，便于调试和性能优化
# 2. prefer_final_fields: 工具面板组件的字段优先使用final，提高性能
# 3. avoid_print: 在开发期间允许使用print调试，但生产代码中应避免
# 4. sized_box_for_whitespace: 使用SizedBox而不是Container来占位空间
# 5. use_build_context_synchronously: 防止异步操作中的context使用问题
#
# 性能优化相关：
# 1. avoid_slow_async_io: 避免阻塞UI的异步IO操作
# 2. prefer_spread_collections: 使用展开操作符提高集合操作性能
# 3. use_string_buffers: 大量字符串拼接使用StringBuffer
#
# 代码质量相关：
# 1. prefer_final_fields/local: 减少不必要的变量重新赋值
# 2. use_const_constructors: 使用const构造器提高编译时优化
# 3. directives_ordering: 保持导入语句的一致性
