// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/unit/core/services/coordinators/performance_data_coordinator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jisu_fund_analyzer/src/core/services/base/i_unified_service.dart'
    as _i2;
import 'package:jisu_fund_analyzer/src/core/services/data/unified_data_service.dart'
    as _i5;
import 'package:jisu_fund_analyzer/src/core/services/performance/unified_performance_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeServiceHealthStatus_0 extends _i1.SmartFake
    implements _i2.ServiceHealthStatus {
  _FakeServiceHealthStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServiceStats_1 extends _i1.SmartFake implements _i2.ServiceStats {
  _FakeServiceStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePerformanceMetrics_2 extends _i1.SmartFake
    implements _i3.PerformanceMetrics {
  _FakePerformanceMetrics_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_3<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCacheStats_4 extends _i1.SmartFake implements _i5.CacheStats {
  _FakeCacheStats_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCacheStatistics_5 extends _i1.SmartFake
    implements _i5.CacheStatistics {
  _FakeCacheStatistics_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ServiceContainer].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceContainer extends _i1.Mock implements _i2.ServiceContainer {
  MockServiceContainer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> registerService<T extends _i2.IUnifiedService>(T? service) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerService,
          [service],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  T getService<T extends _i2.IUnifiedService>() => (super.noSuchMethod(
        Invocation.method(
          #getService,
          [],
        ),
        returnValue: _i6.dummyValue<T>(
          this,
          Invocation.method(
            #getService,
            [],
          ),
        ),
      ) as T);

  @override
  bool isRegistered<T extends _i2.IUnifiedService>() => (super.noSuchMethod(
        Invocation.method(
          #isRegistered,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String> getRegisteredServiceNames() => (super.noSuchMethod(
        Invocation.method(
          #getRegisteredServiceNames,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i2.IUnifiedService? getServiceByName(String? serviceName) =>
      (super.noSuchMethod(Invocation.method(
        #getServiceByName,
        [serviceName],
      )) as _i2.IUnifiedService?);
}

/// A class which mocks [UnifiedPerformanceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnifiedPerformanceService extends _i1.Mock
    implements _i3.UnifiedPerformanceService {
  MockUnifiedPerformanceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get serviceName => (super.noSuchMethod(
        Invocation.getter(#serviceName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#serviceName),
        ),
      ) as String);

  @override
  String get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#version),
        ),
      ) as String);

  @override
  List<String> get dependencies => (super.noSuchMethod(
        Invocation.getter(#dependencies),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i4.Stream<_i3.PerformanceMetrics> get performanceMetricsStream =>
      (super.noSuchMethod(
        Invocation.getter(#performanceMetricsStream),
        returnValue: _i4.Stream<_i3.PerformanceMetrics>.empty(),
      ) as _i4.Stream<_i3.PerformanceMetrics>);

  @override
  _i4.Stream<_i3.MemoryPressureEvent> get memoryPressureStream =>
      (super.noSuchMethod(
        Invocation.getter(#memoryPressureStream),
        returnValue: _i4.Stream<_i3.MemoryPressureEvent>.empty(),
      ) as _i4.Stream<_i3.MemoryPressureEvent>);

  @override
  _i4.Stream<_i3.PerformanceAlert> get performanceAlertsStream =>
      (super.noSuchMethod(
        Invocation.getter(#performanceAlertsStream),
        returnValue: _i4.Stream<_i3.PerformanceAlert>.empty(),
      ) as _i4.Stream<_i3.PerformanceAlert>);

  @override
  _i2.ServiceLifecycleState get lifecycleState => (super.noSuchMethod(
        Invocation.getter(#lifecycleState),
        returnValue: _i2.ServiceLifecycleState.uninitialized,
      ) as _i2.ServiceLifecycleState);

  @override
  _i4.Future<void> initialize(_i2.ServiceContainer? container) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [container],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.ServiceHealthStatus> checkHealth() => (super.noSuchMethod(
        Invocation.method(
          #checkHealth,
          [],
        ),
        returnValue: _i4.Future<_i2.ServiceHealthStatus>.value(
            _FakeServiceHealthStatus_0(
          this,
          Invocation.method(
            #checkHealth,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ServiceHealthStatus>);

  @override
  _i2.ServiceStats getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue: _FakeServiceStats_1(
          this,
          Invocation.method(
            #getStats,
            [],
          ),
        ),
      ) as _i2.ServiceStats);

  @override
  _i4.Future<_i3.PerformanceMetrics> getCurrentPerformanceMetrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPerformanceMetrics,
          [],
        ),
        returnValue:
            _i4.Future<_i3.PerformanceMetrics>.value(_FakePerformanceMetrics_2(
          this,
          Invocation.method(
            #getCurrentPerformanceMetrics,
            [],
          ),
        )),
      ) as _i4.Future<_i3.PerformanceMetrics>);

  @override
  _i4.Future<void> optimizePerformance({bool? aggressive = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #optimizePerformance,
          [],
          {#aggressive: aggressive},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<T>> processBatch<T>(
    List<T>? items,
    _i4.Future<T> Function(T)? processor,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processBatch,
          [
            items,
            processor,
          ],
        ),
        returnValue: _i4.Future<List<T>>.value(<T>[]),
      ) as _i4.Future<List<T>>);

  @override
  _i4.Future<List<int>> compressData(List<int>? data) => (super.noSuchMethod(
        Invocation.method(
          #compressData,
          [data],
        ),
        returnValue: _i4.Future<List<int>>.value(<int>[]),
      ) as _i4.Future<List<int>>);

  @override
  _i4.Future<List<int>> decompressData(List<int>? compressedData) =>
      (super.noSuchMethod(
        Invocation.method(
          #decompressData,
          [compressedData],
        ),
        returnValue: _i4.Future<List<int>>.value(<int>[]),
      ) as _i4.Future<List<int>>);

  @override
  List<T> deduplicateData<T>(
    List<T>? items, {
    String Function(T)? keyExtractor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deduplicateData,
          [items],
          {#keyExtractor: keyExtractor},
        ),
        returnValue: <T>[],
      ) as List<T>);

  @override
  void setLifecycleState(_i2.ServiceLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #setLifecycleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UnifiedDataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnifiedDataService extends _i1.Mock
    implements _i5.UnifiedDataService {
  MockUnifiedDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get serviceName => (super.noSuchMethod(
        Invocation.getter(#serviceName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#serviceName),
        ),
      ) as String);

  @override
  String get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#version),
        ),
      ) as String);

  @override
  List<String> get dependencies => (super.noSuchMethod(
        Invocation.getter(#dependencies),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i2.ServiceLifecycleState get lifecycleState => (super.noSuchMethod(
        Invocation.getter(#lifecycleState),
        returnValue: _i2.ServiceLifecycleState.uninitialized,
      ) as _i2.ServiceLifecycleState);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i4.Stream<_i5.DataOperationEvent> get dataOperationStream =>
      (super.noSuchMethod(
        Invocation.getter(#dataOperationStream),
        returnValue: _i4.Stream<_i5.DataOperationEvent>.empty(),
      ) as _i4.Stream<_i5.DataOperationEvent>);

  @override
  _i4.Stream<_i5.CacheMetricsEvent> get cacheMetricsStream =>
      (super.noSuchMethod(
        Invocation.getter(#cacheMetricsStream),
        returnValue: _i4.Stream<_i5.CacheMetricsEvent>.empty(),
      ) as _i4.Stream<_i5.CacheMetricsEvent>);

  @override
  _i4.Stream<_i5.DataSyncEvent> get dataSyncStream => (super.noSuchMethod(
        Invocation.getter(#dataSyncStream),
        returnValue: _i4.Stream<_i5.DataSyncEvent>.empty(),
      ) as _i4.Stream<_i5.DataSyncEvent>);

  @override
  _i5.DataSyncStatus get syncStatus => (super.noSuchMethod(
        Invocation.getter(#syncStatus),
        returnValue: _i5.DataSyncStatus.idle,
      ) as _i5.DataSyncStatus);

  @override
  void setLifecycleState(_i2.ServiceLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #setLifecycleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> initialize(_i2.ServiceContainer? container) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [container],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.ServiceHealthStatus> checkHealth() => (super.noSuchMethod(
        Invocation.method(
          #checkHealth,
          [],
        ),
        returnValue: _i4.Future<_i2.ServiceHealthStatus>.value(
            _FakeServiceHealthStatus_0(
          this,
          Invocation.method(
            #checkHealth,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ServiceHealthStatus>);

  @override
  _i2.ServiceStats getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue: _FakeServiceStats_1(
          this,
          Invocation.method(
            #getStats,
            [],
          ),
        ),
      ) as _i2.ServiceStats);

  @override
  _i4.Future<void> set<T>(
    String? key,
    T? data, {
    Duration? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            key,
            data,
          ],
          {#ttl: ttl},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<T?> get<T>(
    String? key, {
    T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
          {#fromJson: fromJson},
        ),
        returnValue: _i4.Future<T?>.value(),
      ) as _i4.Future<T?>);

  @override
  _i4.Future<T> lazyLoad<T>(
    String? key,
    _i4.Future<T> Function()? loader, {
    Duration? ttl,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lazyLoad,
          [
            key,
            loader,
          ],
          {
            #ttl: ttl,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #lazyLoad,
                  [
                    key,
                    loader,
                  ],
                  {
                    #ttl: ttl,
                    #forceRefresh: forceRefresh,
                  },
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #lazyLoad,
                [
                  key,
                  loader,
                ],
                {
                  #ttl: ttl,
                  #forceRefresh: forceRefresh,
                },
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<_i5.CacheStats> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i4.Future<_i5.CacheStats>.value(_FakeCacheStats_4(
          this,
          Invocation.method(
            #getStatistics,
            [],
          ),
        )),
      ) as _i4.Future<_i5.CacheStats>);

  @override
  _i4.Future<void> cleanup() => (super.noSuchMethod(
        Invocation.method(
          #cleanup,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<T?> getCachedData<T>(
    String? key, {
    T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedData,
          [key],
          {#fromJson: fromJson},
        ),
        returnValue: _i4.Future<T?>.value(),
      ) as _i4.Future<T?>);

  @override
  _i4.Future<void> setCachedData<T>(
    String? key,
    T? data, {
    Duration? ttl,
    T Function(T)? toJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCachedData,
          [
            key,
            data,
          ],
          {
            #ttl: ttl,
            #toJson: toJson,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeCachedData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeCachedData,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<T> lazyLoadData<T>(
    String? key,
    _i4.Future<T> Function()? loader, {
    Duration? ttl,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lazyLoadData,
          [
            key,
            loader,
          ],
          {
            #ttl: ttl,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #lazyLoadData,
                  [
                    key,
                    loader,
                  ],
                  {
                    #ttl: ttl,
                    #forceRefresh: forceRefresh,
                  },
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #lazyLoadData,
                [
                  key,
                  loader,
                ],
                {
                  #ttl: ttl,
                  #forceRefresh: forceRefresh,
                },
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<void> preloadData<T>(
    List<String>? keys,
    _i4.Future<T> Function(String)? loader,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #preloadData,
          [
            keys,
            loader,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<dynamic>> getBatchFundData(List<String>? fundCodes) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchFundData,
          [fundCodes],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  List<T> deduplicateData<T>(
    List<T>? items, {
    String Function(T)? keyExtractor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deduplicateData,
          [items],
          {#keyExtractor: keyExtractor},
        ),
        returnValue: <T>[],
      ) as List<T>);

  @override
  _i4.Future<_i5.CacheStatistics> getCacheStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStatistics,
          [],
        ),
        returnValue:
            _i4.Future<_i5.CacheStatistics>.value(_FakeCacheStatistics_5(
          this,
          Invocation.method(
            #getCacheStatistics,
            [],
          ),
        )),
      ) as _i4.Future<_i5.CacheStatistics>);

  @override
  _i4.Future<void> optimizeCacheStrategy() => (super.noSuchMethod(
        Invocation.method(
          #optimizeCacheStrategy,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> performDataSync({bool? forceSync = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #performDataSync,
          [],
          {#forceSync: forceSync},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
