// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/widgets/unified_fund_search_bar_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:jisu_fund_analyzer/src/bloc/fund_search_bloc.dart' as _i4;
import 'package:jisu_fund_analyzer/src/models/fund_info.dart' as _i5;
import 'package:jisu_fund_analyzer/src/services/fund_analysis_service.dart'
    as _i2;
import 'package:jisu_fund_analyzer/src/services/unified_search_service/i_unified_search_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFundAnalysisService_0 extends _i1.SmartFake
    implements _i2.FundAnalysisService {
  _FakeFundAnalysisService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifiedSearchService_1 extends _i1.SmartFake
    implements _i3.IUnifiedSearchService {
  _FakeIUnifiedSearchService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFundSearchState_2 extends _i1.SmartFake
    implements _i4.FundSearchState {
  _FakeFundSearchState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FundSearchBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockFundSearchBloc extends _i1.Mock implements _i4.FundSearchBloc {
  MockFundSearchBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.FundInfo> get currentFunds => (super.noSuchMethod(
        Invocation.getter(#currentFunds),
        returnValue: <_i5.FundInfo>[],
      ) as List<_i5.FundInfo>);

  @override
  String get currentQuery => (super.noSuchMethod(
        Invocation.getter(#currentQuery),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#currentQuery),
        ),
      ) as String);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  _i2.FundAnalysisService get analysisService => (super.noSuchMethod(
        Invocation.getter(#analysisService),
        returnValue: _FakeFundAnalysisService_0(
          this,
          Invocation.getter(#analysisService),
        ),
      ) as _i2.FundAnalysisService);

  @override
  _i3.IUnifiedSearchService get unifiedSearchService => (super.noSuchMethod(
        Invocation.getter(#unifiedSearchService),
        returnValue: _FakeIUnifiedSearchService_1(
          this,
          Invocation.getter(#unifiedSearchService),
        ),
      ) as _i3.IUnifiedSearchService);

  @override
  _i4.FundSearchState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeFundSearchState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.FundSearchState);

  @override
  _i7.Stream<_i4.FundSearchState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i4.FundSearchState>.empty(),
      ) as _i7.Stream<_i4.FundSearchState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  List<String> getSearchSuggestions(String? prefix) => (super.noSuchMethod(
        Invocation.method(
          #getSearchSuggestions,
          [prefix],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void quickSearch(String? query) => super.noSuchMethod(
        Invocation.method(
          #quickSearch,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void preciseSearch(String? query) => super.noSuchMethod(
        Invocation.method(
          #preciseSearch,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void comprehensiveSearch(String? query) => super.noSuchMethod(
        Invocation.method(
          #comprehensiveSearch,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void autoSearch(String? query) => super.noSuchMethod(
        Invocation.method(
          #autoSearch,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void getSuggestions(String? prefix) => super.noSuchMethod(
        Invocation.method(
          #getSuggestions,
          [prefix],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i4.FundSearchEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i4.FundSearchEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.FundSearchState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i4.FundSearchEvent>(
    _i8.EventHandler<E, _i4.FundSearchState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i8.Transition<_i4.FundSearchEvent, _i4.FundSearchState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void onChange(_i8.Change<_i4.FundSearchState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
