// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/services/api_gateway_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i3;
import 'package:jisu_fund_analyzer/src/features/fund/domain/entities/fund_ranking.dart'
    as _i5;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/entities/portfolio_holding.dart'
    as _i6;
import 'package:jisu_fund_analyzer/src/services/interfaces/service_interfaces.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T1> extends _i1.SmartFake
    implements _i2.ApiResponse<T1> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServiceResult_1<T> extends _i1.SmartFake
    implements _i2.ServiceResult<T> {
  _FakeServiceResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIApiService extends _i1.Mock implements _i2.IApiService {
  MockIApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
    Duration? timeout,
    bool? enableRetry,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #headers: headers,
            #timeout: timeout,
            #enableRetry: enableRetry,
          },
        ),
        returnValue: _i4.Future<_i2.ApiResponse<T>>.value(_FakeApiResponse_0<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #headers: headers,
              #timeout: timeout,
              #enableRetry: enableRetry,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<T>>);

  @override
  _i4.Future<_i2.ApiResponse<T>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
    Duration? timeout,
    bool? enableRetry,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #headers: headers,
            #timeout: timeout,
            #enableRetry: enableRetry,
          },
        ),
        returnValue: _i4.Future<_i2.ApiResponse<T>>.value(_FakeApiResponse_0<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #headers: headers,
              #timeout: timeout,
              #enableRetry: enableRetry,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<T>>);

  @override
  _i4.Future<_i2.ApiResponse<T>> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
    Duration? timeout,
    bool? enableRetry,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #headers: headers,
            #timeout: timeout,
            #enableRetry: enableRetry,
          },
        ),
        returnValue: _i4.Future<_i2.ApiResponse<T>>.value(_FakeApiResponse_0<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #headers: headers,
              #timeout: timeout,
              #enableRetry: enableRetry,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<T>>);

  @override
  _i4.Future<_i2.ApiResponse<T>> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
    Duration? timeout,
    bool? enableRetry,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #headers: headers,
            #timeout: timeout,
            #enableRetry: enableRetry,
          },
        ),
        returnValue: _i4.Future<_i2.ApiResponse<T>>.value(_FakeApiResponse_0<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #headers: headers,
              #timeout: timeout,
              #enableRetry: enableRetry,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<T>>);

  @override
  _i4.Future<bool> testConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #testConnectivity,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void setBaseUrl(String? url) => super.noSuchMethod(
        Invocation.method(
          #setBaseUrl,
          [url],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addFallbackUrl(String? url) => super.noSuchMethod(
        Invocation.method(
          #addFallbackUrl,
          [url],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getServiceStats() => (super.noSuchMethod(
        Invocation.method(
          #getServiceStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<bool> checkHealth() => (super.noSuchMethod(
        Invocation.method(
          #checkHealth,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [IFundDataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIFundDataService extends _i1.Mock implements _i2.IFundDataService {
  MockIFundDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ServiceResult<List<_i5.FundRanking>>> getFundRankings({
    String? symbol,
    bool? forceRefresh,
    dynamic Function(double)? onProgress,
    bool? useHighPerformance,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFundRankings,
          [],
          {
            #symbol: symbol,
            #forceRefresh: forceRefresh,
            #onProgress: onProgress,
            #useHighPerformance: useHighPerformance,
          },
        ),
        returnValue: _i4.Future<_i2.ServiceResult<List<_i5.FundRanking>>>.value(
            _FakeServiceResult_1<List<_i5.FundRanking>>(
          this,
          Invocation.method(
            #getFundRankings,
            [],
            {
              #symbol: symbol,
              #forceRefresh: forceRefresh,
              #onProgress: onProgress,
              #useHighPerformance: useHighPerformance,
            },
          ),
        )),
      ) as _i4.Future<_i2.ServiceResult<List<_i5.FundRanking>>>);

  @override
  _i4.Future<_i2.ServiceResult<List<_i5.FundRanking>>> searchFunds(
    String? query, {
    List<_i5.FundRanking>? searchIn,
    bool? useHighPerformance,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFunds,
          [query],
          {
            #searchIn: searchIn,
            #useHighPerformance: useHighPerformance,
          },
        ),
        returnValue: _i4.Future<_i2.ServiceResult<List<_i5.FundRanking>>>.value(
            _FakeServiceResult_1<List<_i5.FundRanking>>(
          this,
          Invocation.method(
            #searchFunds,
            [query],
            {
              #searchIn: searchIn,
              #useHighPerformance: useHighPerformance,
            },
          ),
        )),
      ) as _i4.Future<_i2.ServiceResult<List<_i5.FundRanking>>>);

  @override
  _i4.Future<_i2.ServiceResult<Map<String, dynamic>>> getFundDetail(
          String? fundCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFundDetail,
          [fundCode],
        ),
        returnValue: _i4.Future<_i2.ServiceResult<Map<String, dynamic>>>.value(
            _FakeServiceResult_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getFundDetail,
            [fundCode],
          ),
        )),
      ) as _i4.Future<_i2.ServiceResult<Map<String, dynamic>>>);

  @override
  _i4.Future<void> preheatCache() => (super.noSuchMethod(
        Invocation.method(
          #preheatCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCache({String? symbol}) => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
          {#symbol: symbol},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  Map<String, dynamic> getServiceStats() => (super.noSuchMethod(
        Invocation.method(
          #getServiceStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<bool> checkHealth() => (super.noSuchMethod(
        Invocation.method(
          #checkHealth,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [IPortfolioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPortfolioService extends _i1.Mock implements _i2.IPortfolioService {
  MockIPortfolioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.Either<_i2.Failure, List<_i6.PortfolioHolding>>>
      getUserHoldings(
    String? userId, {
    bool? useCache,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getUserHoldings,
              [userId],
              {#useCache: useCache},
            ),
            returnValue: _i4.Future<
                    _i3.Either<_i2.Failure, List<_i6.PortfolioHolding>>>.value(
                _FakeEither_2<_i2.Failure, List<_i6.PortfolioHolding>>(
              this,
              Invocation.method(
                #getUserHoldings,
                [userId],
                {#useCache: useCache},
              ),
            )),
          ) as _i4.Future<_i3.Either<_i2.Failure, List<_i6.PortfolioHolding>>>);

  @override
  _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>> saveUserHoldings(
    String? userId,
    List<_i6.PortfolioHolding>? holdings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserHoldings,
          [
            userId,
            holdings,
          ],
        ),
        returnValue: _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>>.value(
            _FakeEither_2<_i2.Failure, _i3.Unit>(
          this,
          Invocation.method(
            #saveUserHoldings,
            [
              userId,
              holdings,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>>);

  @override
  _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>> addHolding(
    String? userId,
    _i6.PortfolioHolding? holding,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addHolding,
          [
            userId,
            holding,
          ],
        ),
        returnValue: _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>>.value(
            _FakeEither_2<_i2.Failure, _i3.Unit>(
          this,
          Invocation.method(
            #addHolding,
            [
              userId,
              holding,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>>);

  @override
  _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>> removeHolding(
    String? userId,
    String? fundCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeHolding,
          [
            userId,
            fundCode,
          ],
        ),
        returnValue: _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>>.value(
            _FakeEither_2<_i2.Failure, _i3.Unit>(
          this,
          Invocation.method(
            #removeHolding,
            [
              userId,
              fundCode,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>>);

  @override
  _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>> updateHolding(
    String? userId,
    _i6.PortfolioHolding? holding,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHolding,
          [
            userId,
            holding,
          ],
        ),
        returnValue: _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>>.value(
            _FakeEither_2<_i2.Failure, _i3.Unit>(
          this,
          Invocation.method(
            #updateHolding,
            [
              userId,
              holding,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>>);

  @override
  _i4.Future<_i3.Either<_i2.Failure, _i2.IPortfolioProfitSummary>>
      calculatePortfolioProfit(
    String? userId, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #calculatePortfolioProfit,
              [userId],
              {
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue: _i4.Future<
                    _i3.Either<_i2.Failure, _i2.IPortfolioProfitSummary>>.value(
                _FakeEither_2<_i2.Failure, _i2.IPortfolioProfitSummary>(
              this,
              Invocation.method(
                #calculatePortfolioProfit,
                [userId],
                {
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i4
              .Future<_i3.Either<_i2.Failure, _i2.IPortfolioProfitSummary>>);

  @override
  _i4.Future<_i3.Either<_i2.Failure, _i2.IPortfolioAnalysisReport>>
      getPortfolioAnalysis(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getPortfolioAnalysis,
              [userId],
            ),
            returnValue: _i4.Future<
                    _i3
                    .Either<_i2.Failure, _i2.IPortfolioAnalysisReport>>.value(
                _FakeEither_2<_i2.Failure, _i2.IPortfolioAnalysisReport>(
              this,
              Invocation.method(
                #getPortfolioAnalysis,
                [userId],
              ),
            )),
          ) as _i4
              .Future<_i3.Either<_i2.Failure, _i2.IPortfolioAnalysisReport>>);

  @override
  _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>> convertFavoriteToHolding(
    String? userId,
    String? fundCode, {
    double? customAmount,
    int? customShares,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertFavoriteToHolding,
          [
            userId,
            fundCode,
          ],
          {
            #customAmount: customAmount,
            #customShares: customShares,
          },
        ),
        returnValue: _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>>.value(
            _FakeEither_2<_i2.Failure, _i3.Unit>(
          this,
          Invocation.method(
            #convertFavoriteToHolding,
            [
              userId,
              fundCode,
            ],
            {
              #customAmount: customAmount,
              #customShares: customShares,
            },
          ),
        )),
      ) as _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>>);

  @override
  _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>> clearUserHoldings(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearUserHoldings,
          [userId],
        ),
        returnValue: _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>>.value(
            _FakeEither_2<_i2.Failure, _i3.Unit>(
          this,
          Invocation.method(
            #clearUserHoldings,
            [userId],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i2.Failure, _i3.Unit>>);

  @override
  Map<String, dynamic> getServiceStats() => (super.noSuchMethod(
        Invocation.method(
          #getServiceStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<bool> checkHealth() => (super.noSuchMethod(
        Invocation.method(
          #checkHealth,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
