// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/services/unified_portfolio_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dartz/dartz.dart' as _i2;
import 'package:hive/hive.dart' as _i19;
import 'package:jisu_fund_analyzer/src/core/cache/interfaces/cache_service.dart'
    as _i6;
import 'package:jisu_fund_analyzer/src/features/portfolio/data/services/fund_favorite_service.dart'
    as _i17;
import 'package:jisu_fund_analyzer/src/features/portfolio/data/services/portfolio_profit_api_service.dart'
    as _i8;
import 'package:jisu_fund_analyzer/src/features/portfolio/data/services/portfolio_profit_cache_service.dart'
    as _i13;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/entities/fund_corporate_action.dart'
    as _i11;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/entities/fund_split_detail.dart'
    as _i12;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/entities/portfolio_holding.dart'
    as _i10;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/entities/portfolio_profit_calculation_criteria.dart'
    as _i15;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/entities/portfolio_profit_metrics.dart'
    as _i3;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/entities/portfolio_summary.dart'
    as _i4;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/fund_favorite/src/entities/fund_favorite.dart'
    as _i18;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/fund_favorite/src/entities/fund_favorite_list.dart'
    as _i5;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/repositories/portfolio_profit_repository.dart'
    as _i9;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/services/portfolio_profit_calculation_engine.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePortfolioProfitMetrics_1 extends _i1.SmartFake
    implements _i3.PortfolioProfitMetrics {
  _FakePortfolioProfitMetrics_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePortfolioSummary_2 extends _i1.SmartFake
    implements _i4.PortfolioSummary {
  _FakePortfolioSummary_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFundFavoriteList_3 extends _i1.SmartFake
    implements _i5.FundFavoriteList {
  _FakeFundFavoriteList_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i6.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<T?> get<T>(String? key) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
        ),
        returnValue: _i7.Future<T?>.value(),
      ) as _i7.Future<T?>);

  @override
  _i7.Future<void> put<T>(
    String? key,
    T? value, {
    Duration? expiration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
          {#expiration: expiration},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<String>> getAllKeys() => (super.noSuchMethod(
        Invocation.method(
          #getAllKeys,
          [],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<Map<String, dynamic>> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getAll(List<String>? keys) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [keys],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> putAll(
    Map<String, dynamic>? keyValuePairs, {
    Duration? expiration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [keyValuePairs],
          {#expiration: expiration},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeAll(List<String>? keys) => (super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [keys],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setExpiration(
    String? key,
    Duration? expiration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setExpiration,
          [
            key,
            expiration,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Duration?> getExpiration(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getExpiration,
          [key],
        ),
        returnValue: _i7.Future<Duration?>.value(),
      ) as _i7.Future<Duration?>);
}

/// A class which mocks [PortfolioProfitApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioProfitApiService extends _i1.Mock
    implements _i8.PortfolioProfitApiService {
  MockPortfolioProfitApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<
      _i2.Either<_i9.Failure, List<_i10.PortfolioHolding>>> getUserHoldings(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserHoldings,
          [userId],
        ),
        returnValue: _i7
            .Future<_i2.Either<_i9.Failure, List<_i10.PortfolioHolding>>>.value(
            _FakeEither_0<_i9.Failure, List<_i10.PortfolioHolding>>(
          this,
          Invocation.method(
            #getUserHoldings,
            [userId],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i9.Failure, List<_i10.PortfolioHolding>>>);

  @override
  _i7.Future<_i2.Either<_i9.Failure, Map<DateTime, double>>> getFundNavHistory({
    required String? fundCode,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFundNavHistory,
          [],
          {
            #fundCode: fundCode,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i7.Future<_i2.Either<_i9.Failure, Map<DateTime, double>>>.value(
                _FakeEither_0<_i9.Failure, Map<DateTime, double>>(
          this,
          Invocation.method(
            #getFundNavHistory,
            [],
            {
              #fundCode: fundCode,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i7.Future<_i2.Either<_i9.Failure, Map<DateTime, double>>>);

  @override
  _i7.Future<_i2.Either<_i9.Failure, Map<DateTime, double>>>
      getFundAccumulatedNavHistory({
    required String? fundCode,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getFundAccumulatedNavHistory,
              [],
              {
                #fundCode: fundCode,
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue: _i7
                .Future<_i2.Either<_i9.Failure, Map<DateTime, double>>>.value(
                _FakeEither_0<_i9.Failure, Map<DateTime, double>>(
              this,
              Invocation.method(
                #getFundAccumulatedNavHistory,
                [],
                {
                  #fundCode: fundCode,
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i7.Future<_i2.Either<_i9.Failure, Map<DateTime, double>>>);

  @override
  _i7.Future<_i2.Either<_i9.Failure, Map<DateTime, double>>>
      getBenchmarkHistory({
    required String? benchmarkCode,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getBenchmarkHistory,
              [],
              {
                #benchmarkCode: benchmarkCode,
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue: _i7
                .Future<_i2.Either<_i9.Failure, Map<DateTime, double>>>.value(
                _FakeEither_0<_i9.Failure, Map<DateTime, double>>(
              this,
              Invocation.method(
                #getBenchmarkHistory,
                [],
                {
                  #benchmarkCode: benchmarkCode,
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i7.Future<_i2.Either<_i9.Failure, Map<DateTime, double>>>);

  @override
  _i7.Future<_i2.Either<_i9.Failure, List<_i11.FundCorporateAction>>>
      getFundDividendHistory({
    required String? fundCode,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getFundDividendHistory,
              [],
              {
                #fundCode: fundCode,
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue: _i7.Future<
                    _i2
                    .Either<_i9.Failure, List<_i11.FundCorporateAction>>>.value(
                _FakeEither_0<_i9.Failure, List<_i11.FundCorporateAction>>(
              this,
              Invocation.method(
                #getFundDividendHistory,
                [],
                {
                  #fundCode: fundCode,
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i7
              .Future<_i2.Either<_i9.Failure, List<_i11.FundCorporateAction>>>);

  @override
  _i7.Future<_i2.Either<_i9.Failure, List<_i12.FundSplitDetail>>>
      getFundSplitHistory({
    required String? fundCode,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getFundSplitHistory,
              [],
              {
                #fundCode: fundCode,
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue: _i7.Future<
                    _i2.Either<_i9.Failure, List<_i12.FundSplitDetail>>>.value(
                _FakeEither_0<_i9.Failure, List<_i12.FundSplitDetail>>(
              this,
              Invocation.method(
                #getFundSplitHistory,
                [],
                {
                  #fundCode: fundCode,
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i7.Future<_i2.Either<_i9.Failure, List<_i12.FundSplitDetail>>>);

  @override
  _i7.Future<_i2.Either<_i9.Failure, List<_i9.BenchmarkIndex>>>
      getSupportedBenchmarkIndices() => (super.noSuchMethod(
            Invocation.method(
              #getSupportedBenchmarkIndices,
              [],
            ),
            returnValue: _i7.Future<
                    _i2.Either<_i9.Failure, List<_i9.BenchmarkIndex>>>.value(
                _FakeEither_0<_i9.Failure, List<_i9.BenchmarkIndex>>(
              this,
              Invocation.method(
                #getSupportedBenchmarkIndices,
                [],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i9.Failure, List<_i9.BenchmarkIndex>>>);

  @override
  _i7.Future<_i2.Either<_i9.Failure, _i9.DataQualityReport>>
      getDataQualityReport({
    required String? fundCode,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getDataQualityReport,
              [],
              {
                #fundCode: fundCode,
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue: _i7
                .Future<_i2.Either<_i9.Failure, _i9.DataQualityReport>>.value(
                _FakeEither_0<_i9.Failure, _i9.DataQualityReport>(
              this,
              Invocation.method(
                #getDataQualityReport,
                [],
                {
                  #fundCode: fundCode,
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i7.Future<_i2.Either<_i9.Failure, _i9.DataQualityReport>>);
}

/// A class which mocks [PortfolioProfitCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioProfitCacheService extends _i1.Mock
    implements _i13.PortfolioProfitCacheService {
  MockPortfolioProfitCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cacheHoldings(
    String? cacheKey,
    List<_i10.PortfolioHolding>? holdings,
    Duration? expiryDuration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheHoldings,
          [
            cacheKey,
            holdings,
            expiryDuration,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i10.PortfolioHolding>?> getCachedHoldings(
          String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedHoldings,
          [cacheKey],
        ),
        returnValue: _i7.Future<List<_i10.PortfolioHolding>?>.value(),
      ) as _i7.Future<List<_i10.PortfolioHolding>?>);

  @override
  _i7.Future<void> cacheNavHistory(
    String? cacheKey,
    Map<DateTime, double>? navHistory,
    Duration? expiryDuration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheNavHistory,
          [
            cacheKey,
            navHistory,
            expiryDuration,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<DateTime, double>?> getCachedNavHistory(String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNavHistory,
          [cacheKey],
        ),
        returnValue: _i7.Future<Map<DateTime, double>?>.value(),
      ) as _i7.Future<Map<DateTime, double>?>);

  @override
  _i7.Future<void> cacheBenchmarkHistory(
    String? cacheKey,
    Map<DateTime, double>? benchmarkHistory,
    Duration? expiryDuration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheBenchmarkHistory,
          [
            cacheKey,
            benchmarkHistory,
            expiryDuration,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<DateTime, double>?> getCachedBenchmarkHistory(
          String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedBenchmarkHistory,
          [cacheKey],
        ),
        returnValue: _i7.Future<Map<DateTime, double>?>.value(),
      ) as _i7.Future<Map<DateTime, double>?>);

  @override
  _i7.Future<void> cacheDividendHistory(
    String? cacheKey,
    List<_i11.FundCorporateAction>? dividendHistory,
    Duration? expiryDuration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheDividendHistory,
          [
            cacheKey,
            dividendHistory,
            expiryDuration,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i11.FundCorporateAction>?> getCachedDividendHistory(
          String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedDividendHistory,
          [cacheKey],
        ),
        returnValue: _i7.Future<List<_i11.FundCorporateAction>?>.value(),
      ) as _i7.Future<List<_i11.FundCorporateAction>?>);

  @override
  _i7.Future<void> cacheSplitHistory(
    String? cacheKey,
    List<_i12.FundSplitDetail>? splitHistory,
    Duration? expiryDuration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheSplitHistory,
          [
            cacheKey,
            splitHistory,
            expiryDuration,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i12.FundSplitDetail>?> getCachedSplitHistory(
          String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedSplitHistory,
          [cacheKey],
        ),
        returnValue: _i7.Future<List<_i12.FundSplitDetail>?>.value(),
      ) as _i7.Future<List<_i12.FundSplitDetail>?>);

  @override
  _i7.Future<void> cacheProfitMetrics({
    required String? cacheKey,
    required _i3.PortfolioProfitMetrics? metrics,
    required Duration? expiryDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProfitMetrics,
          [],
          {
            #cacheKey: cacheKey,
            #metrics: metrics,
            #expiryDuration: expiryDuration,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.PortfolioProfitMetrics?> getCachedProfitMetrics(
          String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedProfitMetrics,
          [cacheKey],
        ),
        returnValue: _i7.Future<_i3.PortfolioProfitMetrics?>.value(),
      ) as _i7.Future<_i3.PortfolioProfitMetrics?>);

  @override
  _i7.Future<void> clearExpiredCache() => (super.noSuchMethod(
        Invocation.method(
          #clearExpiredCache,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cacheBenchmarkIndices(
    String? cacheKey,
    List<_i13.BenchmarkIndex>? indices,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheBenchmarkIndices,
          [
            cacheKey,
            indices,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i13.BenchmarkIndex>?> getCachedBenchmarkIndices(
          String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedBenchmarkIndices,
          [cacheKey],
        ),
        returnValue: _i7.Future<List<_i13.BenchmarkIndex>?>.value(),
      ) as _i7.Future<List<_i13.BenchmarkIndex>?>);

  @override
  _i7.Future<void> cacheDataQualityReport(
    String? cacheKey,
    _i13.DataQualityReport? report,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheDataQualityReport,
          [
            cacheKey,
            report,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i13.DataQualityReport?> getCachedDataQualityReport(
          String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedDataQualityReport,
          [cacheKey],
        ),
        returnValue: _i7.Future<_i13.DataQualityReport?>.value(),
      ) as _i7.Future<_i13.DataQualityReport?>);

  @override
  _i7.Future<void> clearPortfolioCache() => (super.noSuchMethod(
        Invocation.method(
          #clearPortfolioCache,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [PortfolioProfitCalculationEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioProfitCalculationEngine extends _i1.Mock
    implements _i14.PortfolioProfitCalculationEngine {
  MockPortfolioProfitCalculationEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.PortfolioProfitMetrics> calculateFundProfitMetrics({
    required _i10.PortfolioHolding? holding,
    required _i15.PortfolioProfitCalculationCriteria? criteria,
    Map<DateTime, double>? navHistory,
    Map<DateTime, double>? benchmarkHistory,
    List<_i11.FundCorporateAction>? corporateActions,
    List<_i12.FundSplitDetail>? splitDetails,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateFundProfitMetrics,
          [],
          {
            #holding: holding,
            #criteria: criteria,
            #navHistory: navHistory,
            #benchmarkHistory: benchmarkHistory,
            #corporateActions: corporateActions,
            #splitDetails: splitDetails,
          },
        ),
        returnValue: _i7.Future<_i3.PortfolioProfitMetrics>.value(
            _FakePortfolioProfitMetrics_1(
          this,
          Invocation.method(
            #calculateFundProfitMetrics,
            [],
            {
              #holding: holding,
              #criteria: criteria,
              #navHistory: navHistory,
              #benchmarkHistory: benchmarkHistory,
              #corporateActions: corporateActions,
              #splitDetails: splitDetails,
            },
          ),
        )),
      ) as _i7.Future<_i3.PortfolioProfitMetrics>);

  @override
  _i7.Future<_i4.PortfolioSummary> calculatePortfolioSummary({
    required List<_i10.PortfolioHolding>? holdings,
    required _i15.PortfolioProfitCalculationCriteria? criteria,
    Map<String, Map<DateTime, double>>? allNavHistory,
    Map<String, _i3.PortfolioProfitMetrics>? allMetrics,
    Map<String, List<_i11.FundCorporateAction>>? allCorporateActions,
    Map<String, List<_i12.FundSplitDetail>>? allSplitDetails,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePortfolioSummary,
          [],
          {
            #holdings: holdings,
            #criteria: criteria,
            #allNavHistory: allNavHistory,
            #allMetrics: allMetrics,
            #allCorporateActions: allCorporateActions,
            #allSplitDetails: allSplitDetails,
          },
        ),
        returnValue:
            _i7.Future<_i4.PortfolioSummary>.value(_FakePortfolioSummary_2(
          this,
          Invocation.method(
            #calculatePortfolioSummary,
            [],
            {
              #holdings: holdings,
              #criteria: criteria,
              #allNavHistory: allNavHistory,
              #allMetrics: allMetrics,
              #allCorporateActions: allCorporateActions,
              #allSplitDetails: allSplitDetails,
            },
          ),
        )),
      ) as _i7.Future<_i4.PortfolioSummary>);

  @override
  _i7.Future<Map<String, _i3.PortfolioProfitMetrics>>
      calculateMultiDimensionalComparison({
    required List<_i10.PortfolioHolding>? holdings,
    required List<_i15.CalculationFrequency>? frequencies,
    _i15.PortfolioProfitCalculationCriteria? baseCriteria,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #calculateMultiDimensionalComparison,
              [],
              {
                #holdings: holdings,
                #frequencies: frequencies,
                #baseCriteria: baseCriteria,
              },
            ),
            returnValue:
                _i7.Future<Map<String, _i3.PortfolioProfitMetrics>>.value(
                    <String, _i3.PortfolioProfitMetrics>{}),
          ) as _i7.Future<Map<String, _i3.PortfolioProfitMetrics>>);

  @override
  String generateCacheKey(
    _i10.PortfolioHolding? holding,
    _i15.PortfolioProfitCalculationCriteria? criteria,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateCacheKey,
          [
            holding,
            criteria,
          ],
        ),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.method(
            #generateCacheKey,
            [
              holding,
              criteria,
            ],
          ),
        ),
      ) as String);

  @override
  _i7.Future<_i2.Either<_i9.Failure, _i3.PortfolioProfitMetrics>>
      calculateFundMetrics({
    required _i10.PortfolioHolding? holding,
    required _i15.PortfolioProfitCalculationCriteria? criteria,
    Map<DateTime, double>? navHistory,
    Map<DateTime, double>? benchmarkHistory,
    List<_i11.FundCorporateAction>? dividendHistory,
    List<_i12.FundSplitDetail>? splitHistory,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #calculateFundMetrics,
              [],
              {
                #holding: holding,
                #criteria: criteria,
                #navHistory: navHistory,
                #benchmarkHistory: benchmarkHistory,
                #dividendHistory: dividendHistory,
                #splitHistory: splitHistory,
              },
            ),
            returnValue: _i7.Future<
                    _i2.Either<_i9.Failure, _i3.PortfolioProfitMetrics>>.value(
                _FakeEither_0<_i9.Failure, _i3.PortfolioProfitMetrics>(
              this,
              Invocation.method(
                #calculateFundMetrics,
                [],
                {
                  #holding: holding,
                  #criteria: criteria,
                  #navHistory: navHistory,
                  #benchmarkHistory: benchmarkHistory,
                  #dividendHistory: dividendHistory,
                  #splitHistory: splitHistory,
                },
              ),
            )),
          ) as _i7.Future<_i2.Either<_i9.Failure, _i3.PortfolioProfitMetrics>>);

  @override
  _i7.Future<bool> validateCriteria(
          _i15.PortfolioProfitCalculationCriteria? criteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateCriteria,
          [criteria],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i2.Either<_i9.Failure, _i9.DataQualityReport>>
      analyzeDataQuality({
    required String? fundCode,
    required Map<DateTime, double>? navHistory,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #analyzeDataQuality,
              [],
              {
                #fundCode: fundCode,
                #navHistory: navHistory,
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue: _i7
                .Future<_i2.Either<_i9.Failure, _i9.DataQualityReport>>.value(
                _FakeEither_0<_i9.Failure, _i9.DataQualityReport>(
              this,
              Invocation.method(
                #analyzeDataQuality,
                [],
                {
                  #fundCode: fundCode,
                  #navHistory: navHistory,
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i7.Future<_i2.Either<_i9.Failure, _i9.DataQualityReport>>);
}

/// A class which mocks [FundFavoriteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFundFavoriteService extends _i1.Mock
    implements _i17.FundFavoriteService {
  MockFundFavoriteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> resetCache() => (super.noSuchMethod(
        Invocation.method(
          #resetCache,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i18.FundFavorite>> getAllFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getAllFavorites,
          [],
        ),
        returnValue:
            _i7.Future<List<_i18.FundFavorite>>.value(<_i18.FundFavorite>[]),
      ) as _i7.Future<List<_i18.FundFavorite>>);

  @override
  _i7.Future<_i18.FundFavorite?> getFavoriteByCode(String? fundCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteByCode,
          [fundCode],
        ),
        returnValue: _i7.Future<_i18.FundFavorite?>.value(),
      ) as _i7.Future<_i18.FundFavorite?>);

  @override
  _i7.Future<void> addFavorite(_i18.FundFavorite? favorite) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [favorite],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateFavorite(_i18.FundFavorite? favorite) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFavorite,
          [favorite],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeFavorite(String? fundCode) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [fundCode],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeFavorites(List<String>? fundCodes) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorites,
          [fundCodes],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isFavorite(String? fundCode) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [fundCode],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<int> getFavoriteCount() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteCount,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i18.FundFavorite>> searchFavorites(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFavorites,
          [query],
        ),
        returnValue:
            _i7.Future<List<_i18.FundFavorite>>.value(<_i18.FundFavorite>[]),
      ) as _i7.Future<List<_i18.FundFavorite>>);

  @override
  _i7.Future<List<_i18.FundFavorite>> getSortedFavorites({
    _i18.FundFavoriteSortType? sortType = _i18.FundFavoriteSortType.addTime,
    _i18.FundFavoriteSortDirection? direction =
        _i18.FundFavoriteSortDirection.descending,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSortedFavorites,
          [],
          {
            #sortType: sortType,
            #direction: direction,
          },
        ),
        returnValue:
            _i7.Future<List<_i18.FundFavorite>>.value(<_i18.FundFavorite>[]),
      ) as _i7.Future<List<_i18.FundFavorite>>);

  @override
  _i7.Future<void> updateMarketData(
    String? fundCode, {
    double? currentNav,
    double? dailyChange,
    double? previousNav,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMarketData,
          [fundCode],
          {
            #currentNav: currentNav,
            #dailyChange: dailyChange,
            #previousNav: previousNav,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateSortWeight(
    String? fundCode,
    double? weight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSortWeight,
          [
            fundCode,
            weight,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAllFavorites() => (super.noSuchMethod(
        Invocation.method(
          #clearAllFavorites,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.FundFavoriteList>> getAllLists() => (super.noSuchMethod(
        Invocation.method(
          #getAllLists,
          [],
        ),
        returnValue: _i7.Future<List<_i5.FundFavoriteList>>.value(
            <_i5.FundFavoriteList>[]),
      ) as _i7.Future<List<_i5.FundFavoriteList>>);

  @override
  _i7.Future<_i5.FundFavoriteList?> getListById(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListById,
          [listId],
        ),
        returnValue: _i7.Future<_i5.FundFavoriteList?>.value(),
      ) as _i7.Future<_i5.FundFavoriteList?>);

  @override
  _i7.Future<void> createList(_i5.FundFavoriteList? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #createList,
          [list],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateList(_i5.FundFavoriteList? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateList,
          [list],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteList(String? listId) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [listId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.FundFavoriteList> getDefaultList() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultList,
          [],
        ),
        returnValue:
            _i7.Future<_i5.FundFavoriteList>.value(_FakeFundFavoriteList_3(
          this,
          Invocation.method(
            #getDefaultList,
            [],
          ),
        )),
      ) as _i7.Future<_i5.FundFavoriteList>);

  @override
  _i7.Future<void> cleanupExpiredData() => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>> getStorageStats() => (super.noSuchMethod(
        Invocation.method(
          #getStorageStats,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i19.Box<E> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<E> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);

  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
      ) as bool);

  @override
  Iterable<dynamic> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: <dynamic>[],
      ) as Iterable<dynamic>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
      ) as bool);

  @override
  Iterable<E> valuesBetween({
    dynamic startKey,
    dynamic endKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #valuesBetween,
          [],
          {
            #startKey: startKey,
            #endKey: endKey,
          },
        ),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  E? getAt(int? index) => (super.noSuchMethod(Invocation.method(
        #getAt,
        [index],
      )) as E?);

  @override
  Map<dynamic, E> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <dynamic, E>{},
      ) as Map<dynamic, E>);

  @override
  dynamic keyAt(int? index) => super.noSuchMethod(Invocation.method(
        #keyAt,
        [index],
      ));

  @override
  _i7.Stream<_i19.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i7.Stream<_i19.BoxEvent>.empty(),
      ) as _i7.Stream<_i19.BoxEvent>);

  @override
  bool containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> put(
    dynamic key,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> putAt(
    int? index,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> putAll(Map<dynamic, E>? entries) => (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> add(E? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<Iterable<int>> addAll(Iterable<E>? values) => (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i7.Future<Iterable<int>>.value(<int>[]),
      ) as _i7.Future<Iterable<int>>);

  @override
  _i7.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
