// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/services/unified_search_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:jisu_fund_analyzer/src/features/fund/shared/models/fund_ranking.dart'
    as _i4;
import 'package:jisu_fund_analyzer/src/features/fund/shared/services/search_service.dart'
    as _i2;
import 'package:jisu_fund_analyzer/src/services/enhanced_fund_search_service.dart'
    as _i3;
import 'package:jisu_fund_analyzer/src/services/multi_index_search_engine.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSearchResult_0 extends _i1.SmartFake implements _i2.SearchResult {
  _FakeSearchResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchStatistics_1 extends _i1.SmartFake
    implements _i2.SearchStatistics {
  _FakeSearchStatistics_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEnhancedSearchResult_2 extends _i1.SmartFake
    implements _i3.EnhancedSearchResult {
  _FakeEnhancedSearchResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEnhancedSearchStatistics_3 extends _i1.SmartFake
    implements _i3.EnhancedSearchStatistics {
  _FakeEnhancedSearchStatistics_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEnhancedPerformanceReport_4 extends _i1.SmartFake
    implements _i3.EnhancedPerformanceReport {
  _FakeEnhancedPerformanceReport_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEnhancedServiceHealthStatus_5 extends _i1.SmartFake
    implements _i3.EnhancedServiceHealthStatus {
  _FakeEnhancedServiceHealthStatus_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchService extends _i1.Mock implements _i2.SearchService {
  MockSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void buildIndex(List<_i4.FundRanking>? funds) => super.noSuchMethod(
        Invocation.method(
          #buildIndex,
          [funds],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.SearchResult> search(
    String? query, {
    _i2.SearchOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
          {#options: options},
        ),
        returnValue: _i5.Future<_i2.SearchResult>.value(_FakeSearchResult_0(
          this,
          Invocation.method(
            #search,
            [query],
            {#options: options},
          ),
        )),
      ) as _i5.Future<_i2.SearchResult>);

  @override
  List<String> getSearchSuggestions(
    String? query, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchSuggestions,
          [query],
          {#limit: limit},
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> getRecentSearches([int? limit = 10]) => (super.noSuchMethod(
        Invocation.method(
          #getRecentSearches,
          [limit],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void clearSearchHistory() => super.noSuchMethod(
        Invocation.method(
          #clearSearchHistory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.SearchStatistics getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _FakeSearchStatistics_1(
          this,
          Invocation.method(
            #getStatistics,
            [],
          ),
        ),
      ) as _i2.SearchStatistics);
}

/// A class which mocks [EnhancedFundSearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnhancedFundSearchService extends _i1.Mock
    implements _i3.EnhancedFundSearchService {
  MockEnhancedFundSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.EnhancedSearchResult> searchFunds(
    String? query, {
    _i3.EnhancedSearchOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFunds,
          [query],
          {#options: options},
        ),
        returnValue: _i5.Future<_i3.EnhancedSearchResult>.value(
            _FakeEnhancedSearchResult_2(
          this,
          Invocation.method(
            #searchFunds,
            [query],
            {#options: options},
          ),
        )),
      ) as _i5.Future<_i3.EnhancedSearchResult>);

  @override
  _i5.Future<_i3.EnhancedSearchResult> multiCriteriaSearch(
          _i6.MultiCriteriaCriteria? criteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #multiCriteriaSearch,
          [criteria],
        ),
        returnValue: _i5.Future<_i3.EnhancedSearchResult>.value(
            _FakeEnhancedSearchResult_2(
          this,
          Invocation.method(
            #multiCriteriaSearch,
            [criteria],
          ),
        )),
      ) as _i5.Future<_i3.EnhancedSearchResult>);

  @override
  _i5.Future<List<String>> getSmartSearchSuggestions(
    String? prefix, {
    int? maxSuggestions = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSmartSearchSuggestions,
          [prefix],
          {#maxSuggestions: maxSuggestions},
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> warmupSearchCache() => (super.noSuchMethod(
        Invocation.method(
          #warmupSearchCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refreshFundData({bool? forceRefresh = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshFundData,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i3.EnhancedSearchStatistics getEnhancedSearchStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getEnhancedSearchStatistics,
          [],
        ),
        returnValue: _FakeEnhancedSearchStatistics_3(
          this,
          Invocation.method(
            #getEnhancedSearchStatistics,
            [],
          ),
        ),
      ) as _i3.EnhancedSearchStatistics);

  @override
  _i5.Future<_i3.EnhancedPerformanceReport> getEnhancedPerformanceReport() =>
      (super.noSuchMethod(
        Invocation.method(
          #getEnhancedPerformanceReport,
          [],
        ),
        returnValue: _i5.Future<_i3.EnhancedPerformanceReport>.value(
            _FakeEnhancedPerformanceReport_4(
          this,
          Invocation.method(
            #getEnhancedPerformanceReport,
            [],
          ),
        )),
      ) as _i5.Future<_i3.EnhancedPerformanceReport>);

  @override
  _i5.Future<List<_i3.EnhancedPerformanceIssue>>
      diagnoseEnhancedPerformanceIssues() => (super.noSuchMethod(
            Invocation.method(
              #diagnoseEnhancedPerformanceIssues,
              [],
            ),
            returnValue: _i5.Future<List<_i3.EnhancedPerformanceIssue>>.value(
                <_i3.EnhancedPerformanceIssue>[]),
          ) as _i5.Future<List<_i3.EnhancedPerformanceIssue>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> loadIncrementalHistoryData(
    String? fundCode, {
    int? days = 30,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadIncrementalHistoryData,
          [fundCode],
          {
            #days: days,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> triggerBehaviorPreload(String? fundCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #triggerBehaviorPreload,
          [fundCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i3.EnhancedServiceHealthStatus getEnhancedServiceHealthStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getEnhancedServiceHealthStatus,
          [],
        ),
        returnValue: _FakeEnhancedServiceHealthStatus_5(
          this,
          Invocation.method(
            #getEnhancedServiceHealthStatus,
            [],
          ),
        ),
      ) as _i3.EnhancedServiceHealthStatus);

  @override
  _i5.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
