// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/unit/core/di/service_registry_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:get_it/get_it.dart' as _i2;
import 'package:jisu_fund_analyzer/src/core/di/di_container_manager.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetIt_0 extends _i1.SmartFake implements _i2.GetIt {
  _FakeGetIt_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DIContainerManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDIContainerManager extends _i1.Mock
    implements _i4.DIContainerManager {
  MockDIContainerManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetIt get getIt => (super.noSuchMethod(
        Invocation.getter(#getIt),
        returnValue: _FakeGetIt_0(
          this,
          Invocation.getter(#getIt),
        ),
      ) as _i2.GetIt);

  @override
  int get registeredServicesCount => (super.noSuchMethod(
        Invocation.getter(#registeredServicesCount),
        returnValue: 0,
      ) as int);

  @override
  Map<String, String> get registeredServices => (super.noSuchMethod(
        Invocation.getter(#registeredServices),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  List<String> get registeredServiceNames => (super.noSuchMethod(
        Invocation.getter(#registeredServiceNames),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get isConfigured => (super.noSuchMethod(
        Invocation.getter(#isConfigured),
        returnValue: false,
      ) as bool);

  @override
  String get currentEnvironment => (super.noSuchMethod(
        Invocation.getter(#currentEnvironment),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#currentEnvironment),
        ),
      ) as String);

  @override
  bool get isDevelopment => (super.noSuchMethod(
        Invocation.getter(#isDevelopment),
        returnValue: false,
      ) as bool);

  @override
  bool get isTesting => (super.noSuchMethod(
        Invocation.getter(#isTesting),
        returnValue: false,
      ) as bool);

  @override
  bool get isProduction => (super.noSuchMethod(
        Invocation.getter(#isProduction),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> get containerStatus => (super.noSuchMethod(
        Invocation.getter(#containerStatus),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i3.Future<void> configure(_i4.DIContainerConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #configure,
          [config],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void registerSingletonInstance<T extends Object>(
    T? instance, {
    String? name,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerSingletonInstance,
          [instance],
          {#name: name},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerLazySingleton<T extends Object>(
    T Function()? factory, {
    String? name,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerLazySingleton,
          [factory],
          {#name: name},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerFactory<T extends Object>(
    T Function()? factory, {
    String? name,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerFactory,
          [factory],
          {#name: name},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> registerAsyncSingleton<T extends Object>(
    _i3.Future<T> Function()? factory, {
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerAsyncSingleton,
          [factory],
          {#name: name},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  T get<T extends Object>() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _i5.dummyValue<T>(
          this,
          Invocation.method(
            #get,
            [],
          ),
        ),
      ) as T);

  @override
  _i3.Future<T> getAsync<T extends Object>() => (super.noSuchMethod(
        Invocation.method(
          #getAsync,
          [],
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #getAsync,
                  [],
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #getAsync,
                [],
              ),
            ),
      ) as _i3.Future<T>);

  @override
  bool isRegistered<T extends Object>() => (super.noSuchMethod(
        Invocation.method(
          #isRegistered,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isServiceNameRegistered(String? name) => (super.noSuchMethod(
        Invocation.method(
          #isServiceNameRegistered,
          [name],
        ),
        returnValue: false,
      ) as bool);

  @override
  String? getServiceRegistrationType(String? name) =>
      (super.noSuchMethod(Invocation.method(
        #getServiceRegistrationType,
        [name],
      )) as String?);

  @override
  _i4.ServiceRegistration? getServiceRegistration(String? name) =>
      (super.noSuchMethod(Invocation.method(
        #getServiceRegistration,
        [name],
      )) as _i4.ServiceRegistration?);

  @override
  _i3.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  T getByName<T extends Object>(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getByName,
          [name],
        ),
        returnValue: _i5.dummyValue<T>(
          this,
          Invocation.method(
            #getByName,
            [name],
          ),
        ),
      ) as T);

  @override
  _i3.Future<void> registerService(_i4.ServiceRegistration? registration) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerService,
          [registration],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> registerBatch(
          List<_i3.Future<void> Function()>? registrations) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerBatch,
          [registrations],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
