// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/features/portfolio/portfolio_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jisu_fund_analyzer/src/models/fund_info.dart' as _i6;
import 'package:jisu_fund_analyzer/src/services/fund_analysis_service.dart'
    as _i3;
import 'package:jisu_fund_analyzer/src/services/high_performance_fund_service.dart'
    as _i5;
import 'package:jisu_fund_analyzer/src/services/portfolio_analysis_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePortfolio_0 extends _i1.SmartFake implements _i2.Portfolio {
  _FakePortfolio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePortfolioSimulation_1 extends _i1.SmartFake
    implements _i2.PortfolioSimulation {
  _FakePortfolioSimulation_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFundRiskMetrics_2 extends _i1.SmartFake
    implements _i3.FundRiskMetrics {
  _FakeFundRiskMetrics_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFundScore_3 extends _i1.SmartFake implements _i3.FundScore {
  _FakeFundScore_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PortfolioAnalysisService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioAnalysisService extends _i1.Mock
    implements _i2.PortfolioAnalysisService {
  MockPortfolioAnalysisService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Portfolio> createPortfolio({
    required String? name,
    required List<_i2.PortfolioHolding>? holdings,
    String? description,
    _i2.PortfolioStrategy? strategy = _i2.PortfolioStrategy.balanced,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPortfolio,
          [],
          {
            #name: name,
            #holdings: holdings,
            #description: description,
            #strategy: strategy,
          },
        ),
        returnValue: _i4.Future<_i2.Portfolio>.value(_FakePortfolio_0(
          this,
          Invocation.method(
            #createPortfolio,
            [],
            {
              #name: name,
              #holdings: holdings,
              #description: description,
              #strategy: strategy,
            },
          ),
        )),
      ) as _i4.Future<_i2.Portfolio>);

  @override
  _i4.Future<_i2.Portfolio> optimizePortfolioWeights({
    required _i2.Portfolio? portfolio,
    _i2.OptimizationGoal? goal = _i2.OptimizationGoal.maximizeSharpe,
    List<String>? constraints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #optimizePortfolioWeights,
          [],
          {
            #portfolio: portfolio,
            #goal: goal,
            #constraints: constraints,
          },
        ),
        returnValue: _i4.Future<_i2.Portfolio>.value(_FakePortfolio_0(
          this,
          Invocation.method(
            #optimizePortfolioWeights,
            [],
            {
              #portfolio: portfolio,
              #goal: goal,
              #constraints: constraints,
            },
          ),
        )),
      ) as _i4.Future<_i2.Portfolio>);

  @override
  _i4.Future<_i2.PortfolioSimulation> simulatePortfolio(
    _i2.Portfolio? portfolio, {
    int? months = 12,
    double? initialInvestment = 10000.0,
    int? simulations = 1000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #simulatePortfolio,
          [portfolio],
          {
            #months: months,
            #initialInvestment: initialInvestment,
            #simulations: simulations,
          },
        ),
        returnValue: _i4.Future<_i2.PortfolioSimulation>.value(
            _FakePortfolioSimulation_1(
          this,
          Invocation.method(
            #simulatePortfolio,
            [portfolio],
            {
              #months: months,
              #initialInvestment: initialInvestment,
              #simulations: simulations,
            },
          ),
        )),
      ) as _i4.Future<_i2.PortfolioSimulation>);

  @override
  _i4.Future<void> clearPortfolioCache() => (super.noSuchMethod(
        Invocation.method(
          #clearPortfolioCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [FundAnalysisService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFundAnalysisService extends _i1.Mock
    implements _i3.FundAnalysisService {
  MockFundAnalysisService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i3.MovingAverageData>> calculateMovingAverage(
    String? fundCode, {
    int? period = 5,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateMovingAverage,
          [fundCode],
          {
            #period: period,
            #useCache: useCache,
          },
        ),
        returnValue: _i4.Future<List<_i3.MovingAverageData>>.value(
            <_i3.MovingAverageData>[]),
      ) as _i4.Future<List<_i3.MovingAverageData>>);

  @override
  _i4.Future<List<_i3.RSIData>> calculateRSI(
    String? fundCode, {
    int? period = 14,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRSI,
          [fundCode],
          {
            #period: period,
            #useCache: useCache,
          },
        ),
        returnValue: _i4.Future<List<_i3.RSIData>>.value(<_i3.RSIData>[]),
      ) as _i4.Future<List<_i3.RSIData>>);

  @override
  _i4.Future<List<_i3.BollingerBandsData>> calculateBollingerBands(
    String? fundCode, {
    int? period = 20,
    double? stdDev = 2.0,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateBollingerBands,
          [fundCode],
          {
            #period: period,
            #stdDev: stdDev,
            #useCache: useCache,
          },
        ),
        returnValue: _i4.Future<List<_i3.BollingerBandsData>>.value(
            <_i3.BollingerBandsData>[]),
      ) as _i4.Future<List<_i3.BollingerBandsData>>);

  @override
  _i4.Future<_i3.FundRiskMetrics> calculateRiskMetrics(
    String? fundCode, {
    int? period = 252,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRiskMetrics,
          [fundCode],
          {
            #period: period,
            #useCache: useCache,
          },
        ),
        returnValue:
            _i4.Future<_i3.FundRiskMetrics>.value(_FakeFundRiskMetrics_2(
          this,
          Invocation.method(
            #calculateRiskMetrics,
            [fundCode],
            {
              #period: period,
              #useCache: useCache,
            },
          ),
        )),
      ) as _i4.Future<_i3.FundRiskMetrics>);

  @override
  _i4.Future<_i3.FundScore> calculateFundScore(String? fundCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateFundScore,
          [fundCode],
        ),
        returnValue: _i4.Future<_i3.FundScore>.value(_FakeFundScore_3(
          this,
          Invocation.method(
            #calculateFundScore,
            [fundCode],
          ),
        )),
      ) as _i4.Future<_i3.FundScore>);

  @override
  _i4.Future<List<_i3.FundScore>> getRecommendedFunds({
    String? fundType = r'全部',
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedFunds,
          [],
          {
            #fundType: fundType,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i3.FundScore>>.value(<_i3.FundScore>[]),
      ) as _i4.Future<List<_i3.FundScore>>);

  @override
  _i4.Future<void> clearAnalysisCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAnalysisCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [HighPerformanceFundService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHighPerformanceFundService extends _i1.Mock
    implements _i5.HighPerformanceFundService {
  MockHighPerformanceFundService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i6.FundInfo> searchFunds(
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFunds,
          [query],
          {#limit: limit},
        ),
        returnValue: <_i6.FundInfo>[],
      ) as List<_i6.FundInfo>);

  @override
  List<_i6.FundInfo> searchFundsMultiple(
    List<String>? queries, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFundsMultiple,
          [queries],
          {#limit: limit},
        ),
        returnValue: <_i6.FundInfo>[],
      ) as List<_i6.FundInfo>);

  @override
  _i4.Future<void> preloadFundData() => (super.noSuchMethod(
        Invocation.method(
          #preloadFundData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadAndCacheFundData({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAndCacheFundData,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  Map<String, dynamic> getCacheInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCacheInfo,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
