// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/unit/core/performance/monitors/memory_leak_detector_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jisu_fund_analyzer/src/core/performance/managers/advanced_memory_manager.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMemoryInfo_0 extends _i1.SmartFake implements _i2.MemoryInfo {
  _FakeMemoryInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdvancedMemoryManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdvancedMemoryManager extends _i1.Mock
    implements _i2.AdvancedMemoryManager {
  MockAdvancedMemoryManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i2.MemoryPressureEvent> get pressureStream => (super.noSuchMethod(
        Invocation.getter(#pressureStream),
        returnValue: _i3.Stream<_i2.MemoryPressureEvent>.empty(),
      ) as _i3.Stream<_i2.MemoryPressureEvent>);

  @override
  _i2.MemoryPressureLevel get currentPressureLevel => (super.noSuchMethod(
        Invocation.getter(#currentPressureLevel),
        returnValue: _i2.MemoryPressureLevel.normal,
      ) as _i2.MemoryPressureLevel);

  @override
  _i2.CacheStrategy get currentStrategy => (super.noSuchMethod(
        Invocation.getter(#currentStrategy),
        returnValue: _i2.CacheStrategy.aggressive,
      ) as _i2.CacheStrategy);

  @override
  _i2.MemoryInfo getMemoryInfo() => (super.noSuchMethod(
        Invocation.method(
          #getMemoryInfo,
          [],
        ),
        returnValue: _FakeMemoryInfo_0(
          this,
          Invocation.method(
            #getMemoryInfo,
            [],
          ),
        ),
      ) as _i2.MemoryInfo);

  @override
  _i3.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> put(
    String? key,
    dynamic value, {
    int? sizeBytes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
          {#sizeBytes: sizeBytes},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  T? get<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as T?);

  @override
  dynamic remove(String? key) => super.noSuchMethod(Invocation.method(
        #remove,
        [key],
      ));

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> performLRUEviction({double? threshold}) =>
      (super.noSuchMethod(
        Invocation.method(
          #performLRUEviction,
          [],
          {#threshold: threshold},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> forceGarbageCollection() => (super.noSuchMethod(
        Invocation.method(
          #forceGarbageCollection,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  Map<String, dynamic> getMemoryStats() => (super.noSuchMethod(
        Invocation.method(
          #getMemoryStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
