// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/unit/features/portfolio/presentation/cubit/fund_favorite_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jisu_fund_analyzer/src/features/portfolio/data/services/fund_favorite_service.dart'
    as _i3;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/fund_favorite/src/entities/fund_favorite.dart'
    as _i5;
import 'package:jisu_fund_analyzer/src/features/portfolio/domain/fund_favorite/src/entities/fund_favorite_list.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFundFavoriteList_0 extends _i1.SmartFake
    implements _i2.FundFavoriteList {
  _FakeFundFavoriteList_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FundFavoriteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFundFavoriteService extends _i1.Mock
    implements _i3.FundFavoriteService {
  MockFundFavoriteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.FundFavorite>> getAllFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getAllFavorites,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.FundFavorite>>.value(<_i5.FundFavorite>[]),
      ) as _i4.Future<List<_i5.FundFavorite>>);

  @override
  _i4.Future<_i5.FundFavorite?> getFavoriteByCode(String? fundCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteByCode,
          [fundCode],
        ),
        returnValue: _i4.Future<_i5.FundFavorite?>.value(),
      ) as _i4.Future<_i5.FundFavorite?>);

  @override
  _i4.Future<void> addFavorite(_i5.FundFavorite? favorite) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [favorite],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateFavorite(_i5.FundFavorite? favorite) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFavorite,
          [favorite],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFavorite(String? fundCode) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [fundCode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFavorites(List<String>? fundCodes) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorites,
          [fundCodes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isFavorite(String? fundCode) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [fundCode],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> getFavoriteCount() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.FundFavorite>> searchFavorites(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFavorites,
          [query],
        ),
        returnValue:
            _i4.Future<List<_i5.FundFavorite>>.value(<_i5.FundFavorite>[]),
      ) as _i4.Future<List<_i5.FundFavorite>>);

  @override
  _i4.Future<List<_i5.FundFavorite>> getSortedFavorites({
    _i5.FundFavoriteSortType? sortType = _i5.FundFavoriteSortType.addTime,
    _i5.FundFavoriteSortDirection? direction =
        _i5.FundFavoriteSortDirection.descending,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSortedFavorites,
          [],
          {
            #sortType: sortType,
            #direction: direction,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.FundFavorite>>.value(<_i5.FundFavorite>[]),
      ) as _i4.Future<List<_i5.FundFavorite>>);

  @override
  _i4.Future<void> updateMarketData(
    String? fundCode, {
    double? currentNav,
    double? dailyChange,
    double? previousNav,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMarketData,
          [fundCode],
          {
            #currentNav: currentNav,
            #dailyChange: dailyChange,
            #previousNav: previousNav,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateSortWeight(
    String? fundCode,
    double? weight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSortWeight,
          [
            fundCode,
            weight,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllFavorites() => (super.noSuchMethod(
        Invocation.method(
          #clearAllFavorites,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.FundFavoriteList>> getAllLists() => (super.noSuchMethod(
        Invocation.method(
          #getAllLists,
          [],
        ),
        returnValue: _i4.Future<List<_i2.FundFavoriteList>>.value(
            <_i2.FundFavoriteList>[]),
      ) as _i4.Future<List<_i2.FundFavoriteList>>);

  @override
  _i4.Future<_i2.FundFavoriteList?> getListById(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListById,
          [listId],
        ),
        returnValue: _i4.Future<_i2.FundFavoriteList?>.value(),
      ) as _i4.Future<_i2.FundFavoriteList?>);

  @override
  _i4.Future<void> createList(_i2.FundFavoriteList? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #createList,
          [list],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateList(_i2.FundFavoriteList? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateList,
          [list],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteList(String? listId) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [listId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.FundFavoriteList> getDefaultList() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultList,
          [],
        ),
        returnValue:
            _i4.Future<_i2.FundFavoriteList>.value(_FakeFundFavoriteList_0(
          this,
          Invocation.method(
            #getDefaultList,
            [],
          ),
        )),
      ) as _i4.Future<_i2.FundFavoriteList>);

  @override
  _i4.Future<void> cleanupExpiredData() => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getStorageStats() => (super.noSuchMethod(
        Invocation.method(
          #getStorageStats,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
