// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/ui/week6_ui_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:jisu_fund_analyzer/src/bloc/fund_search_bloc.dart' as _i4;
import 'package:jisu_fund_analyzer/src/bloc/portfolio_bloc.dart' as _i6;
import 'package:jisu_fund_analyzer/src/models/fund_info.dart' as _i7;
import 'package:jisu_fund_analyzer/src/services/fund_analysis_service.dart'
    as _i2;
import 'package:jisu_fund_analyzer/src/services/high_performance_fund_service.dart'
    as _i11;
import 'package:jisu_fund_analyzer/src/services/portfolio_analysis_service.dart'
    as _i5;
import 'package:jisu_fund_analyzer/src/services/unified_search_service/i_unified_search_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFundAnalysisService_0 extends _i1.SmartFake
    implements _i2.FundAnalysisService {
  _FakeFundAnalysisService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIUnifiedSearchService_1 extends _i1.SmartFake
    implements _i3.IUnifiedSearchService {
  _FakeIUnifiedSearchService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFundSearchState_2 extends _i1.SmartFake
    implements _i4.FundSearchState {
  _FakeFundSearchState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePortfolioAnalysisService_3 extends _i1.SmartFake
    implements _i5.PortfolioAnalysisService {
  _FakePortfolioAnalysisService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePortfolioState_4 extends _i1.SmartFake
    implements _i6.PortfolioState {
  _FakePortfolioState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFundRiskMetrics_5 extends _i1.SmartFake
    implements _i2.FundRiskMetrics {
  _FakeFundRiskMetrics_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFundScore_6 extends _i1.SmartFake implements _i2.FundScore {
  _FakeFundScore_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePortfolio_7 extends _i1.SmartFake implements _i5.Portfolio {
  _FakePortfolio_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePortfolioSimulation_8 extends _i1.SmartFake
    implements _i5.PortfolioSimulation {
  _FakePortfolioSimulation_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FundSearchBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockFundSearchBloc extends _i1.Mock implements _i4.FundSearchBloc {
  MockFundSearchBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.FundInfo> get currentFunds => (super.noSuchMethod(
        Invocation.getter(#currentFunds),
        returnValue: <_i7.FundInfo>[],
      ) as List<_i7.FundInfo>);

  @override
  String get currentQuery => (super.noSuchMethod(
        Invocation.getter(#currentQuery),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#currentQuery),
        ),
      ) as String);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  _i2.FundAnalysisService get analysisService => (super.noSuchMethod(
        Invocation.getter(#analysisService),
        returnValue: _FakeFundAnalysisService_0(
          this,
          Invocation.getter(#analysisService),
        ),
      ) as _i2.FundAnalysisService);

  @override
  _i3.IUnifiedSearchService get unifiedSearchService => (super.noSuchMethod(
        Invocation.getter(#unifiedSearchService),
        returnValue: _FakeIUnifiedSearchService_1(
          this,
          Invocation.getter(#unifiedSearchService),
        ),
      ) as _i3.IUnifiedSearchService);

  @override
  _i4.FundSearchState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeFundSearchState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.FundSearchState);

  @override
  _i9.Stream<_i4.FundSearchState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i4.FundSearchState>.empty(),
      ) as _i9.Stream<_i4.FundSearchState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  List<String> getSearchSuggestions(String? prefix) => (super.noSuchMethod(
        Invocation.method(
          #getSearchSuggestions,
          [prefix],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void quickSearch(String? query) => super.noSuchMethod(
        Invocation.method(
          #quickSearch,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void preciseSearch(String? query) => super.noSuchMethod(
        Invocation.method(
          #preciseSearch,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void comprehensiveSearch(String? query) => super.noSuchMethod(
        Invocation.method(
          #comprehensiveSearch,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void autoSearch(String? query) => super.noSuchMethod(
        Invocation.method(
          #autoSearch,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void getSuggestions(String? prefix) => super.noSuchMethod(
        Invocation.method(
          #getSuggestions,
          [prefix],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i4.FundSearchEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i4.FundSearchEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.FundSearchState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i4.FundSearchEvent>(
    _i10.EventHandler<E, _i4.FundSearchState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i10.Transition<_i4.FundSearchEvent, _i4.FundSearchState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void onChange(_i10.Change<_i4.FundSearchState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PortfolioBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioBloc extends _i1.Mock implements _i6.PortfolioBloc {
  MockPortfolioBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.Portfolio> get portfolios => (super.noSuchMethod(
        Invocation.getter(#portfolios),
        returnValue: <_i5.Portfolio>[],
      ) as List<_i5.Portfolio>);

  @override
  List<_i6.FundRecommendation> get recommendedFunds => (super.noSuchMethod(
        Invocation.getter(#recommendedFunds),
        returnValue: <_i6.FundRecommendation>[],
      ) as List<_i6.FundRecommendation>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isOperationInProgress => (super.noSuchMethod(
        Invocation.getter(#isOperationInProgress),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  _i5.PortfolioAnalysisService get portfolioService => (super.noSuchMethod(
        Invocation.getter(#portfolioService),
        returnValue: _FakePortfolioAnalysisService_3(
          this,
          Invocation.getter(#portfolioService),
        ),
      ) as _i5.PortfolioAnalysisService);

  @override
  _i6.PortfolioState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePortfolioState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.PortfolioState);

  @override
  _i9.Stream<_i6.PortfolioState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i6.PortfolioState>.empty(),
      ) as _i9.Stream<_i6.PortfolioState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i6.PortfolioEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.PortfolioEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i6.PortfolioState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.PortfolioEvent>(
    _i10.EventHandler<E, _i6.PortfolioState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i10.Transition<_i6.PortfolioEvent, _i6.PortfolioState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void onChange(_i10.Change<_i6.PortfolioState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FundAnalysisService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFundAnalysisService extends _i1.Mock
    implements _i2.FundAnalysisService {
  MockFundAnalysisService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.MovingAverageData>> calculateMovingAverage(
    String? fundCode, {
    int? period = 5,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateMovingAverage,
          [fundCode],
          {
            #period: period,
            #useCache: useCache,
          },
        ),
        returnValue: _i9.Future<List<_i2.MovingAverageData>>.value(
            <_i2.MovingAverageData>[]),
      ) as _i9.Future<List<_i2.MovingAverageData>>);

  @override
  _i9.Future<List<_i2.RSIData>> calculateRSI(
    String? fundCode, {
    int? period = 14,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRSI,
          [fundCode],
          {
            #period: period,
            #useCache: useCache,
          },
        ),
        returnValue: _i9.Future<List<_i2.RSIData>>.value(<_i2.RSIData>[]),
      ) as _i9.Future<List<_i2.RSIData>>);

  @override
  _i9.Future<List<_i2.BollingerBandsData>> calculateBollingerBands(
    String? fundCode, {
    int? period = 20,
    double? stdDev = 2.0,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateBollingerBands,
          [fundCode],
          {
            #period: period,
            #stdDev: stdDev,
            #useCache: useCache,
          },
        ),
        returnValue: _i9.Future<List<_i2.BollingerBandsData>>.value(
            <_i2.BollingerBandsData>[]),
      ) as _i9.Future<List<_i2.BollingerBandsData>>);

  @override
  _i9.Future<_i2.FundRiskMetrics> calculateRiskMetrics(
    String? fundCode, {
    int? period = 252,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRiskMetrics,
          [fundCode],
          {
            #period: period,
            #useCache: useCache,
          },
        ),
        returnValue:
            _i9.Future<_i2.FundRiskMetrics>.value(_FakeFundRiskMetrics_5(
          this,
          Invocation.method(
            #calculateRiskMetrics,
            [fundCode],
            {
              #period: period,
              #useCache: useCache,
            },
          ),
        )),
      ) as _i9.Future<_i2.FundRiskMetrics>);

  @override
  _i9.Future<_i2.FundScore> calculateFundScore(String? fundCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateFundScore,
          [fundCode],
        ),
        returnValue: _i9.Future<_i2.FundScore>.value(_FakeFundScore_6(
          this,
          Invocation.method(
            #calculateFundScore,
            [fundCode],
          ),
        )),
      ) as _i9.Future<_i2.FundScore>);

  @override
  _i9.Future<List<_i2.FundScore>> getRecommendedFunds({
    String? fundType = r'全部',
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedFunds,
          [],
          {
            #fundType: fundType,
            #limit: limit,
          },
        ),
        returnValue: _i9.Future<List<_i2.FundScore>>.value(<_i2.FundScore>[]),
      ) as _i9.Future<List<_i2.FundScore>>);

  @override
  _i9.Future<void> clearAnalysisCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAnalysisCache,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [PortfolioAnalysisService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioAnalysisService extends _i1.Mock
    implements _i5.PortfolioAnalysisService {
  MockPortfolioAnalysisService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i5.Portfolio> createPortfolio({
    required String? name,
    required List<_i5.PortfolioHolding>? holdings,
    String? description,
    _i5.PortfolioStrategy? strategy = _i5.PortfolioStrategy.balanced,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPortfolio,
          [],
          {
            #name: name,
            #holdings: holdings,
            #description: description,
            #strategy: strategy,
          },
        ),
        returnValue: _i9.Future<_i5.Portfolio>.value(_FakePortfolio_7(
          this,
          Invocation.method(
            #createPortfolio,
            [],
            {
              #name: name,
              #holdings: holdings,
              #description: description,
              #strategy: strategy,
            },
          ),
        )),
      ) as _i9.Future<_i5.Portfolio>);

  @override
  _i9.Future<_i5.Portfolio> optimizePortfolioWeights({
    required _i5.Portfolio? portfolio,
    _i5.OptimizationGoal? goal = _i5.OptimizationGoal.maximizeSharpe,
    List<String>? constraints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #optimizePortfolioWeights,
          [],
          {
            #portfolio: portfolio,
            #goal: goal,
            #constraints: constraints,
          },
        ),
        returnValue: _i9.Future<_i5.Portfolio>.value(_FakePortfolio_7(
          this,
          Invocation.method(
            #optimizePortfolioWeights,
            [],
            {
              #portfolio: portfolio,
              #goal: goal,
              #constraints: constraints,
            },
          ),
        )),
      ) as _i9.Future<_i5.Portfolio>);

  @override
  _i9.Future<_i5.PortfolioSimulation> simulatePortfolio(
    _i5.Portfolio? portfolio, {
    int? months = 12,
    double? initialInvestment = 10000.0,
    int? simulations = 1000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #simulatePortfolio,
          [portfolio],
          {
            #months: months,
            #initialInvestment: initialInvestment,
            #simulations: simulations,
          },
        ),
        returnValue: _i9.Future<_i5.PortfolioSimulation>.value(
            _FakePortfolioSimulation_8(
          this,
          Invocation.method(
            #simulatePortfolio,
            [portfolio],
            {
              #months: months,
              #initialInvestment: initialInvestment,
              #simulations: simulations,
            },
          ),
        )),
      ) as _i9.Future<_i5.PortfolioSimulation>);

  @override
  _i9.Future<void> clearPortfolioCache() => (super.noSuchMethod(
        Invocation.method(
          #clearPortfolioCache,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [HighPerformanceFundService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHighPerformanceFundService extends _i1.Mock
    implements _i11.HighPerformanceFundService {
  MockHighPerformanceFundService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  List<_i7.FundInfo> searchFunds(
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFunds,
          [query],
          {#limit: limit},
        ),
        returnValue: <_i7.FundInfo>[],
      ) as List<_i7.FundInfo>);

  @override
  List<_i7.FundInfo> searchFundsMultiple(
    List<String>? queries, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFundsMultiple,
          [queries],
          {#limit: limit},
        ),
        returnValue: <_i7.FundInfo>[],
      ) as List<_i7.FundInfo>);

  @override
  _i9.Future<void> preloadFundData() => (super.noSuchMethod(
        Invocation.method(
          #preloadFundData,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> loadAndCacheFundData({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAndCacheFundData,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  Map<String, dynamic> getCacheInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCacheInfo,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i9.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}
