// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/unit/core/performance/processors/adaptive_batch_sizer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jisu_fund_analyzer/src/core/performance/managers/advanced_memory_manager.dart'
    as _i3;
import 'package:jisu_fund_analyzer/src/core/performance/monitors/device_performance_detector.dart'
    as _i2;
import 'package:jisu_fund_analyzer/src/core/performance/monitors/memory_pressure_monitor.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDevicePerformanceInfo_0 extends _i1.SmartFake
    implements _i2.DevicePerformanceInfo {
  _FakeDevicePerformanceInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemoryInfo_1 extends _i1.SmartFake implements _i3.MemoryInfo {
  _FakeMemoryInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DeviceCapabilityDetector].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceCapabilityDetector extends _i1.Mock
    implements _i2.DeviceCapabilityDetector {
  MockDeviceCapabilityDetector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.DevicePerformanceInfo> getDevicePerformanceInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDevicePerformanceInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.DevicePerformanceInfo>.value(
            _FakeDevicePerformanceInfo_0(
          this,
          Invocation.method(
            #getDevicePerformanceInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DevicePerformanceInfo>);

  @override
  _i4.Future<_i2.DevicePerformanceInfo> forceDetection() => (super.noSuchMethod(
        Invocation.method(
          #forceDetection,
          [],
        ),
        returnValue: _i4.Future<_i2.DevicePerformanceInfo>.value(
            _FakeDevicePerformanceInfo_0(
          this,
          Invocation.method(
            #forceDetection,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DevicePerformanceInfo>);

  @override
  _i4.Future<bool> isLowEndDevice() => (super.noSuchMethod(
        Invocation.method(
          #isLowEndDevice,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> supportsAdvancedFeatures() => (super.noSuchMethod(
        Invocation.method(
          #supportsAdvancedFeatures,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> getRecommendedConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedConfiguration,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [AdvancedMemoryManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdvancedMemoryManager extends _i1.Mock
    implements _i3.AdvancedMemoryManager {
  MockAdvancedMemoryManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i3.MemoryPressureEvent> get pressureStream => (super.noSuchMethod(
        Invocation.getter(#pressureStream),
        returnValue: _i4.Stream<_i3.MemoryPressureEvent>.empty(),
      ) as _i4.Stream<_i3.MemoryPressureEvent>);

  @override
  _i3.MemoryPressureLevel get currentPressureLevel => (super.noSuchMethod(
        Invocation.getter(#currentPressureLevel),
        returnValue: _i3.MemoryPressureLevel.normal,
      ) as _i3.MemoryPressureLevel);

  @override
  _i3.CacheStrategy get currentStrategy => (super.noSuchMethod(
        Invocation.getter(#currentStrategy),
        returnValue: _i3.CacheStrategy.aggressive,
      ) as _i3.CacheStrategy);

  @override
  _i3.MemoryInfo getMemoryInfo() => (super.noSuchMethod(
        Invocation.method(
          #getMemoryInfo,
          [],
        ),
        returnValue: _FakeMemoryInfo_1(
          this,
          Invocation.method(
            #getMemoryInfo,
            [],
          ),
        ),
      ) as _i3.MemoryInfo);

  @override
  _i4.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> put(
    String? key,
    dynamic value, {
    int? sizeBytes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
          {#sizeBytes: sizeBytes},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  T? get<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as T?);

  @override
  dynamic remove(String? key) => super.noSuchMethod(Invocation.method(
        #remove,
        [key],
      ));

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> performLRUEviction({double? threshold}) =>
      (super.noSuchMethod(
        Invocation.method(
          #performLRUEviction,
          [],
          {#threshold: threshold},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> forceGarbageCollection() => (super.noSuchMethod(
        Invocation.method(
          #forceGarbageCollection,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  Map<String, dynamic> getMemoryStats() => (super.noSuchMethod(
        Invocation.method(
          #getMemoryStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [MemoryPressureMonitor].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryPressureMonitor extends _i1.Mock
    implements _i5.MemoryPressureMonitor {
  MockMemoryPressureMonitor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.MemoryPressureAlert> get alertStream => (super.noSuchMethod(
        Invocation.getter(#alertStream),
        returnValue: _i4.Stream<_i5.MemoryPressureAlert>.empty(),
      ) as _i4.Stream<_i5.MemoryPressureAlert>);

  @override
  _i3.MemoryPressureLevel get currentPressureLevel => (super.noSuchMethod(
        Invocation.getter(#currentPressureLevel),
        returnValue: _i3.MemoryPressureLevel.normal,
      ) as _i3.MemoryPressureLevel);

  @override
  _i4.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.MemoryPressureAlert?> checkMemoryPressure() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkMemoryPressure,
          [],
        ),
        returnValue: _i4.Future<_i5.MemoryPressureAlert?>.value(),
      ) as _i4.Future<_i5.MemoryPressureAlert?>);

  @override
  _i5.MemoryPressureAlertLevel getCurrentPressureLevel() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPressureLevel,
          [],
        ),
        returnValue: _i5.MemoryPressureAlertLevel.info,
      ) as _i5.MemoryPressureAlertLevel);

  @override
  Map<String, dynamic> getMonitoringStats() => (super.noSuchMethod(
        Invocation.method(
          #getMonitoringStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
