// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/unit/core/performance/processors/smart_batch_processor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:jisu_fund_analyzer/src/core/performance/managers/advanced_memory_manager.dart'
    as _i3;
import 'package:jisu_fund_analyzer/src/core/performance/monitors/device_performance_detector.dart'
    as _i2;
import 'package:jisu_fund_analyzer/src/core/performance/processors/backpressure_controller.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDevicePerformanceInfo_0 extends _i1.SmartFake
    implements _i2.DevicePerformanceInfo {
  _FakeDevicePerformanceInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemoryInfo_1 extends _i1.SmartFake implements _i3.MemoryInfo {
  _FakeMemoryInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackpressureMetrics_2 extends _i1.SmartFake
    implements _i4.BackpressureMetrics {
  _FakeBackpressureMetrics_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DeviceCapabilityDetector].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceCapabilityDetector extends _i1.Mock
    implements _i2.DeviceCapabilityDetector {
  MockDeviceCapabilityDetector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.DevicePerformanceInfo> getDevicePerformanceInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDevicePerformanceInfo,
          [],
        ),
        returnValue: _i5.Future<_i2.DevicePerformanceInfo>.value(
            _FakeDevicePerformanceInfo_0(
          this,
          Invocation.method(
            #getDevicePerformanceInfo,
            [],
          ),
        )),
      ) as _i5.Future<_i2.DevicePerformanceInfo>);

  @override
  _i5.Future<_i2.DevicePerformanceInfo> forceDetection() => (super.noSuchMethod(
        Invocation.method(
          #forceDetection,
          [],
        ),
        returnValue: _i5.Future<_i2.DevicePerformanceInfo>.value(
            _FakeDevicePerformanceInfo_0(
          this,
          Invocation.method(
            #forceDetection,
            [],
          ),
        )),
      ) as _i5.Future<_i2.DevicePerformanceInfo>);

  @override
  _i5.Future<bool> isLowEndDevice() => (super.noSuchMethod(
        Invocation.method(
          #isLowEndDevice,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> supportsAdvancedFeatures() => (super.noSuchMethod(
        Invocation.method(
          #supportsAdvancedFeatures,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getRecommendedConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedConfiguration,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
}

/// A class which mocks [AdvancedMemoryManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdvancedMemoryManager extends _i1.Mock
    implements _i3.AdvancedMemoryManager {
  MockAdvancedMemoryManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i3.MemoryPressureEvent> get pressureStream => (super.noSuchMethod(
        Invocation.getter(#pressureStream),
        returnValue: _i5.Stream<_i3.MemoryPressureEvent>.empty(),
      ) as _i5.Stream<_i3.MemoryPressureEvent>);

  @override
  _i3.MemoryPressureLevel get currentPressureLevel => (super.noSuchMethod(
        Invocation.getter(#currentPressureLevel),
        returnValue: _i3.MemoryPressureLevel.normal,
      ) as _i3.MemoryPressureLevel);

  @override
  _i3.CacheStrategy get currentStrategy => (super.noSuchMethod(
        Invocation.getter(#currentStrategy),
        returnValue: _i3.CacheStrategy.aggressive,
      ) as _i3.CacheStrategy);

  @override
  _i3.MemoryInfo getMemoryInfo() => (super.noSuchMethod(
        Invocation.method(
          #getMemoryInfo,
          [],
        ),
        returnValue: _FakeMemoryInfo_1(
          this,
          Invocation.method(
            #getMemoryInfo,
            [],
          ),
        ),
      ) as _i3.MemoryInfo);

  @override
  _i5.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> put(
    String? key,
    dynamic value, {
    int? sizeBytes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
          {#sizeBytes: sizeBytes},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  T? get<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as T?);

  @override
  dynamic remove(String? key) => super.noSuchMethod(Invocation.method(
        #remove,
        [key],
      ));

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> performLRUEviction({double? threshold}) =>
      (super.noSuchMethod(
        Invocation.method(
          #performLRUEviction,
          [],
          {#threshold: threshold},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> forceGarbageCollection() => (super.noSuchMethod(
        Invocation.method(
          #forceGarbageCollection,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic> getMemoryStats() => (super.noSuchMethod(
        Invocation.method(
          #getMemoryStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [BackpressureController].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackpressureController extends _i1.Mock
    implements _i4.BackpressureController {
  MockBackpressureController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BackpressureLevel get currentLevel => (super.noSuchMethod(
        Invocation.getter(#currentLevel),
        returnValue: _i4.BackpressureLevel.none,
      ) as _i4.BackpressureLevel);

  @override
  _i4.BackpressureMetrics get metrics => (super.noSuchMethod(
        Invocation.getter(#metrics),
        returnValue: _FakeBackpressureMetrics_2(
          this,
          Invocation.getter(#metrics),
        ),
      ) as _i4.BackpressureMetrics);

  @override
  List<_i4.BackpressureAction> get actionHistory => (super.noSuchMethod(
        Invocation.getter(#actionHistory),
        returnValue: <_i4.BackpressureAction>[],
      ) as List<_i4.BackpressureAction>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void triggerBackpressure({
    required _i4.BackpressureStrategy? strategy,
    Map<String, dynamic>? parameters,
    String? description,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #triggerBackpressure,
          [],
          {
            #strategy: strategy,
            #parameters: parameters,
            #description: description,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool shouldRejectNewRequest() => (super.noSuchMethod(
        Invocation.method(
          #shouldRejectNewRequest,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool shouldThrottle() => (super.noSuchMethod(
        Invocation.method(
          #shouldThrottle,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool shouldDropLowPriority() => (super.noSuchMethod(
        Invocation.method(
          #shouldDropLowPriority,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  double getCurrentThrottlingFactor() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentThrottlingFactor,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  int getMaxAllowedQueueSize() => (super.noSuchMethod(
        Invocation.method(
          #getMaxAllowedQueueSize,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void recordRejectedRequest() => super.noSuchMethod(
        Invocation.method(
          #recordRejectedRequest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordDroppedItem() => super.noSuchMethod(
        Invocation.method(
          #recordDroppedItem,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordThrottledRequest() => super.noSuchMethod(
        Invocation.method(
          #recordThrottledRequest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addLevelChangeListener(void Function(_i4.BackpressureLevel)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addLevelChangeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeLevelChangeListener(
          void Function(_i4.BackpressureLevel)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeLevelChangeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addMetricsUpdateListener(
          void Function(_i4.BackpressureMetrics)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addMetricsUpdateListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeMetricsUpdateListener(
          void Function(_i4.BackpressureMetrics)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeMetricsUpdateListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addActionListener(void Function(_i4.BackpressureAction)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addActionListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeActionListener(void Function(_i4.BackpressureAction)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeActionListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getPerformanceSummary() => (super.noSuchMethod(
        Invocation.method(
          #getPerformanceSummary,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void pause() => super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resume() => super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void enableBalancedMode() => super.noSuchMethod(
        Invocation.method(
          #enableBalancedMode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void applyBackpressure() => super.noSuchMethod(
        Invocation.method(
          #applyBackpressure,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
