# <!-- Powered by BMAD™ Core -->
markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments:
  - docs/fund-exploration-refactor-brief.md
  - docs/fullstack-architecture.md
devLoadAlwaysFiles:
  - docs/architecture/1-架构概述.md
  - docs/architecture/2-技术栈选择.md
  - docs/prd/1-目标与背景.md
  - docs/prd/2-需求.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
