// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/integration/data_layer_error_handling_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jisu_fund_analyzer/src/core/cache/interfaces/i_unified_cache_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCacheStatistics_0 extends _i1.SmartFake
    implements _i2.CacheStatistics {
  _FakeCacheStatistics_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCacheAccessStats_1 extends _i1.SmartFake
    implements _i2.CacheAccessStats {
  _FakeCacheAccessStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IUnifiedCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUnifiedCacheService extends _i1.Mock
    implements _i2.IUnifiedCacheService {
  MockIUnifiedCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<T?> get<T>(
    String? key, {
    Type? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
          {#type: type},
        ),
        returnValue: _i3.Future<T?>.value(),
      ) as _i3.Future<T?>);

  @override
  _i3.Future<void> put<T>(
    String? key,
    T? data, {
    _i2.CacheConfig? config,
    _i2.CacheMetadata? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            data,
          ],
          {
            #config: config,
            #metadata: metadata,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, T?>> getAll<T>(
    List<String>? keys, {
    Type? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [keys],
          {#type: type},
        ),
        returnValue: _i3.Future<Map<String, T?>>.value(<String, T?>{}),
      ) as _i3.Future<Map<String, T?>>);

  @override
  _i3.Future<void> putAll<T>(
    Map<String, T>? entries, {
    _i2.CacheConfig? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
          {#config: config},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> exists(String? key) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isExpired(String? key) => (super.noSuchMethod(
        Invocation.method(
          #isExpired,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> removeAll(Iterable<String>? keys) => (super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [keys],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> removeByPattern(String? pattern) => (super.noSuchMethod(
        Invocation.method(
          #removeByPattern,
          [pattern],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> clearExpired() => (super.noSuchMethod(
        Invocation.method(
          #clearExpired,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i2.CacheStatistics> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue:
            _i3.Future<_i2.CacheStatistics>.value(_FakeCacheStatistics_0(
          this,
          Invocation.method(
            #getStatistics,
            [],
          ),
        )),
      ) as _i3.Future<_i2.CacheStatistics>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.CacheConfig?> getConfig(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getConfig,
          [key],
        ),
        returnValue: _i3.Future<_i2.CacheConfig?>.value(),
      ) as _i3.Future<_i2.CacheConfig?>);

  @override
  _i3.Future<bool> updateConfig(
    String? key,
    _i2.CacheConfig? config,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConfig,
          [
            key,
            config,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> preload<T>(
    List<String>? keys,
    _i3.Future<T> Function(String)? loader,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #preload,
          [
            keys,
            loader,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i2.CacheAccessStats getAccessStats() => (super.noSuchMethod(
        Invocation.method(
          #getAccessStats,
          [],
        ),
        returnValue: _FakeCacheAccessStats_1(
          this,
          Invocation.method(
            #getAccessStats,
            [],
          ),
        ),
      ) as _i2.CacheAccessStats);

  @override
  void resetAccessStats() => super.noSuchMethod(
        Invocation.method(
          #resetAccessStats,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMonitoringEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setMonitoringEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> optimize() => (super.noSuchMethod(
        Invocation.method(
          #optimize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
