// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/integration/data_layer_performance_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i9;
import 'package:jisu_fund_analyzer/src/core/cache/interfaces/i_unified_cache_service.dart'
    as _i2;
import 'package:jisu_fund_analyzer/src/core/cache/unified_cache_manager.dart'
    as _i8;
import 'package:jisu_fund_analyzer/src/core/data/coordinators/data_layer_coordinator.dart'
    as _i7;
import 'package:jisu_fund_analyzer/src/core/network/intelligent_data_source_switcher.dart'
    as _i5;
import 'package:jisu_fund_analyzer/src/core/network/multi_source_api_config.dart'
    as _i3;
import 'package:jisu_fund_analyzer/src/features/fund/data/services/intelligent_preload_service.dart'
    as _i16;
import 'package:jisu_fund_analyzer/src/features/fund/domain/entities/fund.dart'
    as _i18;
import 'package:jisu_fund_analyzer/src/features/fund/domain/entities/fund_filter_criteria.dart'
    as _i17;
import 'package:jisu_fund_analyzer/src/features/fund/domain/entities/fund_ranking.dart'
    as _i6;
import 'package:jisu_fund_analyzer/src/features/fund/domain/entities/fund_search_criteria.dart'
    as _i19;
import 'package:jisu_fund_analyzer/src/features/fund/presentation/fund_exploration/domain/data/models/fund_dto.dart'
    as _i15;
import 'package:jisu_fund_analyzer/src/features/fund/presentation/fund_exploration/domain/data/services/common_types.dart'
    as _i12;
import 'package:jisu_fund_analyzer/src/features/fund/presentation/fund_exploration/domain/data/services/data_sync_manager.dart'
    as _i11;
import 'package:jisu_fund_analyzer/src/features/fund/presentation/fund_exploration/domain/data/services/optimized_fund_service.dart'
    as _i14;
import 'package:jisu_fund_analyzer/src/features/fund/presentation/fund_exploration/domain/data/services/smart_cache_manager.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCacheStatistics_0 extends _i1.SmartFake
    implements _i2.CacheStatistics {
  _FakeCacheStatistics_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCacheAccessStats_1 extends _i1.SmartFake
    implements _i2.CacheAccessStats {
  _FakeCacheAccessStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiSource_2 extends _i1.SmartFake implements _i3.ApiSource {
  _FakeApiSource_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_3<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataSourceStatusReport_4 extends _i1.SmartFake
    implements _i5.DataSourceStatusReport {
  _FakeDataSourceStatusReport_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_5 extends _i1.SmartFake implements Duration {
  _FakeDuration_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginatedRankingResult_6 extends _i1.SmartFake
    implements _i6.PaginatedRankingResult {
  _FakePaginatedRankingResult_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataLayerHealthReport_7 extends _i1.SmartFake
    implements _i7.DataLayerHealthReport {
  _FakeDataLayerHealthReport_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataLayerPerformanceMetrics_8 extends _i1.SmartFake
    implements _i7.DataLayerPerformanceMetrics {
  _FakeDataLayerPerformanceMetrics_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UnifiedCacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnifiedCacheManager extends _i1.Mock
    implements _i8.UnifiedCacheManager {
  MockUnifiedCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<T?> get<T>(
    String? key, {
    Type? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
          {#type: type},
        ),
        returnValue: _i4.Future<T?>.value(),
      ) as _i4.Future<T?>);

  @override
  _i4.Future<void> put<T>(
    String? key,
    T? data, {
    _i2.CacheConfig? config,
    _i2.CacheMetadata? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            data,
          ],
          {
            #config: config,
            #metadata: metadata,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, T?>> getAll<T>(
    List<String>? keys, {
    Type? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [keys],
          {#type: type},
        ),
        returnValue: _i4.Future<Map<String, T?>>.value(<String, T?>{}),
      ) as _i4.Future<Map<String, T?>>);

  @override
  _i4.Future<void> putAll<T>(
    Map<String, T>? entries, {
    _i2.CacheConfig? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
          {#config: config},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> exists(String? key) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isExpired(String? key) => (super.noSuchMethod(
        Invocation.method(
          #isExpired,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> removeAll(Iterable<String>? keys) => (super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [keys],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> removeByPattern(String? pattern) => (super.noSuchMethod(
        Invocation.method(
          #removeByPattern,
          [pattern],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> clearExpired() => (super.noSuchMethod(
        Invocation.method(
          #clearExpired,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i2.CacheStatistics> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue:
            _i4.Future<_i2.CacheStatistics>.value(_FakeCacheStatistics_0(
          this,
          Invocation.method(
            #getStatistics,
            [],
          ),
        )),
      ) as _i4.Future<_i2.CacheStatistics>);

  @override
  _i4.Future<_i2.CacheConfig?> getConfig(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getConfig,
          [key],
        ),
        returnValue: _i4.Future<_i2.CacheConfig?>.value(),
      ) as _i4.Future<_i2.CacheConfig?>);

  @override
  _i4.Future<bool> updateConfig(
    String? key,
    _i2.CacheConfig? config,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConfig,
          [
            key,
            config,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> preload<T>(
    List<String>? keys,
    _i4.Future<T> Function(String)? loader,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #preload,
          [
            keys,
            loader,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.CacheAccessStats getAccessStats() => (super.noSuchMethod(
        Invocation.method(
          #getAccessStats,
          [],
        ),
        returnValue: _FakeCacheAccessStats_1(
          this,
          Invocation.method(
            #getAccessStats,
            [],
          ),
        ),
      ) as _i2.CacheAccessStats);

  @override
  void resetAccessStats() => super.noSuchMethod(
        Invocation.method(
          #resetAccessStats,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMonitoringEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setMonitoringEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> optimize() => (super.noSuchMethod(
        Invocation.method(
          #optimize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [IntelligentDataSourceSwitcher].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntelligentDataSourceSwitcher extends _i1.Mock
    implements _i5.IntelligentDataSourceSwitcher {
  MockIntelligentDataSourceSwitcher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ApiSource get currentSource => (super.noSuchMethod(
        Invocation.getter(#currentSource),
        returnValue: _FakeApiSource_2(
          this,
          Invocation.getter(#currentSource),
        ),
      ) as _i3.ApiSource);

  @override
  _i4.Stream<_i5.DataSourceEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _i4.Stream<_i5.DataSourceEvent>.empty(),
      ) as _i4.Stream<_i5.DataSourceEvent>);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<T> executeRequest<T>(
    _i4.Future<T> Function(_i9.Dio)? request, {
    String? operationName,
    Duration? timeout,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeRequest,
          [request],
          {
            #operationName: operationName,
            #timeout: timeout,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #executeRequest,
                  [request],
                  {
                    #operationName: operationName,
                    #timeout: timeout,
                    #forceRefresh: forceRefresh,
                  },
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #executeRequest,
                [request],
                {
                  #operationName: operationName,
                  #timeout: timeout,
                  #forceRefresh: forceRefresh,
                },
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i5.DataSourceStatusReport getStatusReport() => (super.noSuchMethod(
        Invocation.method(
          #getStatusReport,
          [],
        ),
        returnValue: _FakeDataSourceStatusReport_4(
          this,
          Invocation.method(
            #getStatusReport,
            [],
          ),
        ),
      ) as _i5.DataSourceStatusReport);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DataSyncManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataSyncManager extends _i1.Mock implements _i11.DataSyncManager {
  MockDataSyncManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, bool>> forceSyncAll() => (super.noSuchMethod(
        Invocation.method(
          #forceSyncAll,
          [],
        ),
        returnValue: _i4.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i4.Future<Map<String, bool>>);

  @override
  _i4.Future<bool> syncDataType(String? dataType) => (super.noSuchMethod(
        Invocation.method(
          #syncDataType,
          [dataType],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  bool needsSync(String? dataType) => (super.noSuchMethod(
        Invocation.method(
          #needsSync,
          [dataType],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i12.SyncState? getSyncState(String? dataType) =>
      (super.noSuchMethod(Invocation.method(
        #getSyncState,
        [dataType],
      )) as _i12.SyncState?);

  @override
  Map<String, _i12.SyncState> getAllSyncStates() => (super.noSuchMethod(
        Invocation.method(
          #getAllSyncStates,
          [],
        ),
        returnValue: <String, _i12.SyncState>{},
      ) as Map<String, _i12.SyncState>);

  @override
  void pauseSync(String? dataType) => super.noSuchMethod(
        Invocation.method(
          #pauseSync,
          [dataType],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumeSync(String? dataType) => super.noSuchMethod(
        Invocation.method(
          #resumeSync,
          [dataType],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSyncInterval(Duration? interval) => super.noSuchMethod(
        Invocation.method(
          #setSyncInterval,
          [interval],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setConflictResolutionStrategy(
          _i12.ConflictResolutionStrategy? strategy) =>
      super.noSuchMethod(
        Invocation.method(
          #setConflictResolutionStrategy,
          [strategy],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getSyncStats() => (super.noSuchMethod(
        Invocation.method(
          #getSyncStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SmartCacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSmartCacheManager extends _i1.Mock implements _i13.SmartCacheManager {
  MockSmartCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> put<T>(
    String? key,
    T? data, {
    Duration? ttl,
    String? dataType = r'unknown',
    bool? persistent = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            data,
          ],
          {
            #ttl: ttl,
            #dataType: dataType,
            #persistent: persistent,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  T? get<T>(
    String? key, {
    bool? refreshOnAccess = false,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #get,
        [key],
        {#refreshOnAccess: refreshOnAccess},
      )) as T?);

  @override
  _i4.Future<void> warmupCache() => (super.noSuchMethod(
        Invocation.method(
          #warmupCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void optimizeCacheSize() => super.noSuchMethod(
        Invocation.method(
          #optimizeCacheSize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [OptimizedFundService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOptimizedFundService extends _i1.Mock
    implements _i14.OptimizedFundService {
  MockOptimizedFundService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i15.FundDto>> getFundBasicInfo({
    int? limit,
    int? offset,
    String? fundType,
    String? company,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFundBasicInfo,
          [],
          {
            #limit: limit,
            #offset: offset,
            #fundType: fundType,
            #company: company,
          },
        ),
        returnValue: _i4.Future<List<_i15.FundDto>>.value(<_i15.FundDto>[]),
      ) as _i4.Future<List<_i15.FundDto>>);

  @override
  _i4.Future<List<_i15.FundRankingDto>> getFundRankings({
    required String? symbol,
    List<String>? fields,
    bool? enableCache = true,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFundRankings,
          [],
          {
            #symbol: symbol,
            #fields: fields,
            #enableCache: enableCache,
            #timeout: timeout,
          },
        ),
        returnValue: _i4.Future<List<_i15.FundRankingDto>>.value(
            <_i15.FundRankingDto>[]),
      ) as _i4.Future<List<_i15.FundRankingDto>>);

  @override
  _i4.Future<void> preloadPopularData() => (super.noSuchMethod(
        Invocation.method(
          #preloadPopularData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i15.FundDto>> loadMoreFunds({
    String? fundType,
    String? company,
    int? batchSize = 5,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMoreFunds,
          [],
          {
            #fundType: fundType,
            #company: company,
            #batchSize: batchSize,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i15.FundDto>>.value(<_i15.FundDto>[]),
      ) as _i4.Future<List<_i15.FundDto>>);

  @override
  _i4.Future<Map<String, dynamic>> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IntelligentPreloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntelligentPreloadService extends _i1.Mock
    implements _i16.IntelligentPreloadService {
  MockIntelligentPreloadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get preloadInterval => (super.noSuchMethod(
        Invocation.getter(#preloadInterval),
        returnValue: _FakeDuration_5(
          this,
          Invocation.getter(#preloadInterval),
        ),
      ) as Duration);

  @override
  int get maxPreloadItems => (super.noSuchMethod(
        Invocation.getter(#maxPreloadItems),
        returnValue: 0,
      ) as int);

  @override
  Duration get maxCacheAge => (super.noSuchMethod(
        Invocation.getter(#maxCacheAge),
        returnValue: _FakeDuration_5(
          this,
          Invocation.getter(#maxCacheAge),
        ),
      ) as Duration);

  @override
  _i4.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void stop() => super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordFilterUsage(_i17.FundFilterCriteria? criteria) =>
      super.noSuchMethod(
        Invocation.method(
          #recordFilterUsage,
          [criteria],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> preloadFilter(_i17.FundFilterCriteria? criteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #preloadFilter,
          [criteria],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> preloadPopularFilters() => (super.noSuchMethod(
        Invocation.method(
          #preloadPopularFilters,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> preloadUserInterestFilters() => (super.noSuchMethod(
        Invocation.method(
          #preloadUserInterestFilters,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> incrementalUpdateFilter(_i17.FundFilterCriteria? criteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementalUpdateFilter,
          [criteria],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  Map<String, dynamic> getPreloadStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getPreloadStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<void> cleanupExpiredData() => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> preloadCommonData() => (super.noSuchMethod(
        Invocation.method(
          #preloadCommonData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void unawaited(_i4.Future<void>? future) => super.noSuchMethod(
        Invocation.method(
          #unawaited,
          [future],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DataLayerCoordinator].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataLayerCoordinator extends _i1.Mock
    implements _i7.DataLayerCoordinator {
  MockDataLayerCoordinator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitializedPublic => (super.noSuchMethod(
        Invocation.getter(#isInitializedPublic),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i18.Fund>> getFunds({
    _i17.FundFilterCriteria? criteria,
    bool? forceRefresh = false,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFunds,
          [],
          {
            #criteria: criteria,
            #forceRefresh: forceRefresh,
            #timeout: timeout,
          },
        ),
        returnValue: _i4.Future<List<_i18.Fund>>.value(<_i18.Fund>[]),
      ) as _i4.Future<List<_i18.Fund>>);

  @override
  _i4.Future<List<_i18.Fund>> searchFunds(
    _i19.FundSearchCriteria? criteria, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFunds,
          [criteria],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<List<_i18.Fund>>.value(<_i18.Fund>[]),
      ) as _i4.Future<List<_i18.Fund>>);

  @override
  _i4.Future<_i6.PaginatedRankingResult> getFundRankings(
    _i6.RankingCriteria? criteria, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFundRankings,
          [criteria],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<_i6.PaginatedRankingResult>.value(
            _FakePaginatedRankingResult_6(
          this,
          Invocation.method(
            #getFundRankings,
            [criteria],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i4.Future<_i6.PaginatedRankingResult>);

  @override
  _i4.Future<Map<String, _i18.Fund>> getBatchFunds(
    List<String>? fundCodes, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchFunds,
          [fundCodes],
          {#forceRefresh: forceRefresh},
        ),
        returnValue:
            _i4.Future<Map<String, _i18.Fund>>.value(<String, _i18.Fund>{}),
      ) as _i4.Future<Map<String, _i18.Fund>>);

  @override
  _i4.Future<bool> refreshCache({_i17.FundFilterCriteria? criteria}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshCache,
          [],
          {#criteria: criteria},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i7.DataLayerHealthReport> getHealthReport() =>
      (super.noSuchMethod(
        Invocation.method(
          #getHealthReport,
          [],
        ),
        returnValue: _i4.Future<_i7.DataLayerHealthReport>.value(
            _FakeDataLayerHealthReport_7(
          this,
          Invocation.method(
            #getHealthReport,
            [],
          ),
        )),
      ) as _i4.Future<_i7.DataLayerHealthReport>);

  @override
  _i4.Future<_i7.DataLayerPerformanceMetrics> getPerformanceMetrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPerformanceMetrics,
          [],
        ),
        returnValue: _i4.Future<_i7.DataLayerPerformanceMetrics>.value(
            _FakeDataLayerPerformanceMetrics_8(
          this,
          Invocation.method(
            #getPerformanceMetrics,
            [],
          ),
        )),
      ) as _i4.Future<_i7.DataLayerPerformanceMetrics>);

  @override
  _i4.Stream<T> getEventStream<T>(String? eventType) => (super.noSuchMethod(
        Invocation.method(
          #getEventStream,
          [eventType],
        ),
        returnValue: _i4.Stream<T>.empty(),
      ) as _i4.Stream<T>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
