// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/integration/story25_performance_system_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:jisu_fund_analyzer/src/core/loading/lazy_loading_manager.dart'
    as _i2;
import 'package:jisu_fund_analyzer/src/core/memory/memory_optimization_manager.dart'
    as _i3;
import 'package:jisu_fund_analyzer/src/core/performance/core_performance_manager.dart'
    as _i11;
import 'package:jisu_fund_analyzer/src/core/performance/managers/advanced_memory_manager.dart'
    as _i4;
import 'package:jisu_fund_analyzer/src/core/performance/monitors/device_performance_detector.dart'
    as _i5;
import 'package:jisu_fund_analyzer/src/core/performance/monitors/memory_leak_detector.dart'
    as _i6;
import 'package:jisu_fund_analyzer/src/core/performance/monitors/memory_pressure_monitor.dart'
    as _i7;
import 'package:jisu_fund_analyzer/src/core/performance/optimizers/adaptive_compression_strategy.dart'
    as _i10;
import 'package:jisu_fund_analyzer/src/core/performance/processors/hybrid_data_parser.dart'
    as _i8;
import 'package:jisu_fund_analyzer/src/core/performance/processors/smart_batch_processor.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLazyLoadingManager_0 extends _i1.SmartFake
    implements _i2.LazyLoadingManager {
  _FakeLazyLoadingManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemoryOptimizationManager_1 extends _i1.SmartFake
    implements _i3.MemoryOptimizationManager {
  _FakeMemoryOptimizationManager_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdvancedMemoryManager_2 extends _i1.SmartFake
    implements _i4.AdvancedMemoryManager {
  _FakeAdvancedMemoryManager_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeviceCapabilityDetector_3 extends _i1.SmartFake
    implements _i5.DeviceCapabilityDetector {
  _FakeDeviceCapabilityDetector_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemoryLeakDetector_4 extends _i1.SmartFake
    implements _i6.MemoryLeakDetector {
  _FakeMemoryLeakDetector_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemoryPressureMonitor_5 extends _i1.SmartFake
    implements _i7.MemoryPressureMonitor {
  _FakeMemoryPressureMonitor_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHybridDataParser_6 extends _i1.SmartFake
    implements _i8.HybridDataParser {
  _FakeHybridDataParser_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSmartBatchProcessor_7<T> extends _i1.SmartFake
    implements _i9.SmartBatchProcessor<T> {
  _FakeSmartBatchProcessor_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdaptiveCompressionStrategy_8 extends _i1.SmartFake
    implements _i10.AdaptiveCompressionStrategy {
  _FakeAdaptiveCompressionStrategy_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePerformanceMetrics_9 extends _i1.SmartFake
    implements _i11.PerformanceMetrics {
  _FakePerformanceMetrics_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemoryInfo_10 extends _i1.SmartFake implements _i4.MemoryInfo {
  _FakeMemoryInfo_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemoryLeakDetectionResult_11 extends _i1.SmartFake
    implements _i6.MemoryLeakDetectionResult {
  _FakeMemoryLeakDetectionResult_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemorySnapshotExtended_12 extends _i1.SmartFake
    implements _i6.MemorySnapshotExtended {
  _FakeMemorySnapshotExtended_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchProcessingMetrics_13 extends _i1.SmartFake
    implements _i9.BatchProcessingMetrics {
  _FakeBatchProcessingMetrics_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompressionResult_14 extends _i1.SmartFake
    implements _i10.CompressionResult {
  _FakeCompressionResult_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CorePerformanceManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCorePerformanceManager extends _i1.Mock
    implements _i11.CorePerformanceManager {
  MockCorePerformanceManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LazyLoadingManager get lazyLoadingManager => (super.noSuchMethod(
        Invocation.getter(#lazyLoadingManager),
        returnValue: _FakeLazyLoadingManager_0(
          this,
          Invocation.getter(#lazyLoadingManager),
        ),
      ) as _i2.LazyLoadingManager);

  @override
  _i3.MemoryOptimizationManager get memoryManager => (super.noSuchMethod(
        Invocation.getter(#memoryManager),
        returnValue: _FakeMemoryOptimizationManager_1(
          this,
          Invocation.getter(#memoryManager),
        ),
      ) as _i3.MemoryOptimizationManager);

  @override
  _i4.AdvancedMemoryManager get advancedMemoryManager => (super.noSuchMethod(
        Invocation.getter(#advancedMemoryManager),
        returnValue: _FakeAdvancedMemoryManager_2(
          this,
          Invocation.getter(#advancedMemoryManager),
        ),
      ) as _i4.AdvancedMemoryManager);

  @override
  _i5.DeviceCapabilityDetector get deviceDetector => (super.noSuchMethod(
        Invocation.getter(#deviceDetector),
        returnValue: _FakeDeviceCapabilityDetector_3(
          this,
          Invocation.getter(#deviceDetector),
        ),
      ) as _i5.DeviceCapabilityDetector);

  @override
  _i6.MemoryLeakDetector get memoryLeakDetector => (super.noSuchMethod(
        Invocation.getter(#memoryLeakDetector),
        returnValue: _FakeMemoryLeakDetector_4(
          this,
          Invocation.getter(#memoryLeakDetector),
        ),
      ) as _i6.MemoryLeakDetector);

  @override
  _i7.MemoryPressureMonitor get memoryPressureMonitor => (super.noSuchMethod(
        Invocation.getter(#memoryPressureMonitor),
        returnValue: _FakeMemoryPressureMonitor_5(
          this,
          Invocation.getter(#memoryPressureMonitor),
        ),
      ) as _i7.MemoryPressureMonitor);

  @override
  _i8.HybridDataParser get hybridDataParser => (super.noSuchMethod(
        Invocation.getter(#hybridDataParser),
        returnValue: _FakeHybridDataParser_6(
          this,
          Invocation.getter(#hybridDataParser),
        ),
      ) as _i8.HybridDataParser);

  @override
  _i9.SmartBatchProcessor<dynamic> get batchProcessor => (super.noSuchMethod(
        Invocation.getter(#batchProcessor),
        returnValue: _FakeSmartBatchProcessor_7<dynamic>(
          this,
          Invocation.getter(#batchProcessor),
        ),
      ) as _i9.SmartBatchProcessor<dynamic>);

  @override
  _i10.AdaptiveCompressionStrategy get compressionStrategy =>
      (super.noSuchMethod(
        Invocation.getter(#compressionStrategy),
        returnValue: _FakeAdaptiveCompressionStrategy_8(
          this,
          Invocation.getter(#compressionStrategy),
        ),
      ) as _i10.AdaptiveCompressionStrategy);

  @override
  _i11.PerformanceStatus get currentStatus => (super.noSuchMethod(
        Invocation.getter(#currentStatus),
        returnValue: _i11.PerformanceStatus.optimal,
      ) as _i11.PerformanceStatus);

  @override
  _i11.OptimizationStrategy get currentStrategy => (super.noSuchMethod(
        Invocation.getter(#currentStrategy),
        returnValue: _i11.OptimizationStrategy.aggressive,
      ) as _i11.OptimizationStrategy);

  @override
  _i12.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void stopPerformanceMonitoring() => super.noSuchMethod(
        Invocation.method(
          #stopPerformanceMonitoring,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.PerformanceMetrics getCurrentMetrics() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentMetrics,
          [],
        ),
        returnValue: _FakePerformanceMetrics_9(
          this,
          Invocation.method(
            #getCurrentMetrics,
            [],
          ),
        ),
      ) as _i11.PerformanceMetrics);

  @override
  List<_i11.PerformanceMetrics> getPerformanceHistory({int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPerformanceHistory,
          [],
          {#limit: limit},
        ),
        returnValue: <_i11.PerformanceMetrics>[],
      ) as List<_i11.PerformanceMetrics>);

  @override
  _i12.Future<void> triggerOptimization(
          {_i11.OptimizationStrategy? strategy}) =>
      (super.noSuchMethod(
        Invocation.method(
          #triggerOptimization,
          [],
          {#strategy: strategy},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> refreshMetrics() => (super.noSuchMethod(
        Invocation.method(
          #refreshMetrics,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  Map<String, dynamic> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String exportPerformanceReport() => (super.noSuchMethod(
        Invocation.method(
          #exportPerformanceReport,
          [],
        ),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #exportPerformanceReport,
            [],
          ),
        ),
      ) as String);

  @override
  void addPerformanceCallback(
          dynamic Function(_i11.PerformanceMetrics)? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #addPerformanceCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addStrategyChangeCallback(
          dynamic Function(_i11.OptimizationStrategy)? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #addStrategyChangeCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addCriticalStateCallback(dynamic Function()? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #addCriticalStateCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removePerformanceCallback(
          dynamic Function(_i11.PerformanceMetrics)? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #removePerformanceCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeStrategyChangeCallback(
          dynamic Function(_i11.OptimizationStrategy)? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #removeStrategyChangeCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeCriticalStateCallback(dynamic Function()? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #removeCriticalStateCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [AdvancedMemoryManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdvancedMemoryManager extends _i1.Mock
    implements _i4.AdvancedMemoryManager {
  MockAdvancedMemoryManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Stream<_i4.MemoryPressureEvent> get pressureStream =>
      (super.noSuchMethod(
        Invocation.getter(#pressureStream),
        returnValue: _i12.Stream<_i4.MemoryPressureEvent>.empty(),
      ) as _i12.Stream<_i4.MemoryPressureEvent>);

  @override
  _i4.MemoryPressureLevel get currentPressureLevel => (super.noSuchMethod(
        Invocation.getter(#currentPressureLevel),
        returnValue: _i4.MemoryPressureLevel.normal,
      ) as _i4.MemoryPressureLevel);

  @override
  _i4.CacheStrategy get currentStrategy => (super.noSuchMethod(
        Invocation.getter(#currentStrategy),
        returnValue: _i4.CacheStrategy.aggressive,
      ) as _i4.CacheStrategy);

  @override
  _i4.MemoryInfo getMemoryInfo() => (super.noSuchMethod(
        Invocation.method(
          #getMemoryInfo,
          [],
        ),
        returnValue: _FakeMemoryInfo_10(
          this,
          Invocation.method(
            #getMemoryInfo,
            [],
          ),
        ),
      ) as _i4.MemoryInfo);

  @override
  _i12.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> put(
    String? key,
    dynamic value, {
    int? sizeBytes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
          {#sizeBytes: sizeBytes},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  T? get<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as T?);

  @override
  dynamic remove(String? key) => super.noSuchMethod(Invocation.method(
        #remove,
        [key],
      ));

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> performLRUEviction({double? threshold}) =>
      (super.noSuchMethod(
        Invocation.method(
          #performLRUEviction,
          [],
          {#threshold: threshold},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> forceGarbageCollection() => (super.noSuchMethod(
        Invocation.method(
          #forceGarbageCollection,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  Map<String, dynamic> getMemoryStats() => (super.noSuchMethod(
        Invocation.method(
          #getMemoryStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [MemoryLeakDetector].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryLeakDetector extends _i1.Mock
    implements _i6.MemoryLeakDetector {
  MockMemoryLeakDetector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Stream<_i6.MemoryLeakDetectionResult> get leakDetectionStream =>
      (super.noSuchMethod(
        Invocation.getter(#leakDetectionStream),
        returnValue: _i12.Stream<_i6.MemoryLeakDetectionResult>.empty(),
      ) as _i12.Stream<_i6.MemoryLeakDetectionResult>);

  @override
  int get leakCount => (super.noSuchMethod(
        Invocation.getter(#leakCount),
        returnValue: 0,
      ) as int);

  @override
  bool get isMonitoring => (super.noSuchMethod(
        Invocation.getter(#isMonitoring),
        returnValue: false,
      ) as bool);

  @override
  void configure(_i6.MemoryLeakDetectorConfig? config) => super.noSuchMethod(
        Invocation.method(
          #configure,
          [config],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void start() => super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i6.MemoryLeakDetectionResult> detectLeak() =>
      (super.noSuchMethod(
        Invocation.method(
          #detectLeak,
          [],
        ),
        returnValue: _i12.Future<_i6.MemoryLeakDetectionResult>.value(
            _FakeMemoryLeakDetectionResult_11(
          this,
          Invocation.method(
            #detectLeak,
            [],
          ),
        )),
      ) as _i12.Future<_i6.MemoryLeakDetectionResult>);

  @override
  _i12.Future<void> forceGarbageCollection() => (super.noSuchMethod(
        Invocation.method(
          #forceGarbageCollection,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i6.MemorySnapshotExtended> getCurrentSnapshot() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentSnapshot,
          [],
        ),
        returnValue: _i12.Future<_i6.MemorySnapshotExtended>.value(
            _FakeMemorySnapshotExtended_12(
          this,
          Invocation.method(
            #getCurrentSnapshot,
            [],
          ),
        )),
      ) as _i12.Future<_i6.MemorySnapshotExtended>);

  @override
  List<_i6.MemorySnapshotExtended> getSnapshotHistory() => (super.noSuchMethod(
        Invocation.method(
          #getSnapshotHistory,
          [],
        ),
        returnValue: <_i6.MemorySnapshotExtended>[],
      ) as List<_i6.MemorySnapshotExtended>);

  @override
  Map<String, dynamic> getMemoryTrends() => (super.noSuchMethod(
        Invocation.method(
          #getMemoryTrends,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [MemoryPressureMonitor].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryPressureMonitor extends _i1.Mock
    implements _i7.MemoryPressureMonitor {
  MockMemoryPressureMonitor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Stream<_i7.MemoryPressureAlert> get alertStream => (super.noSuchMethod(
        Invocation.getter(#alertStream),
        returnValue: _i12.Stream<_i7.MemoryPressureAlert>.empty(),
      ) as _i12.Stream<_i7.MemoryPressureAlert>);

  @override
  _i4.MemoryPressureLevel get currentPressureLevel => (super.noSuchMethod(
        Invocation.getter(#currentPressureLevel),
        returnValue: _i4.MemoryPressureLevel.normal,
      ) as _i4.MemoryPressureLevel);

  @override
  _i12.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i7.MemoryPressureAlert?> checkMemoryPressure() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkMemoryPressure,
          [],
        ),
        returnValue: _i12.Future<_i7.MemoryPressureAlert?>.value(),
      ) as _i12.Future<_i7.MemoryPressureAlert?>);

  @override
  _i7.MemoryPressureAlertLevel getCurrentPressureLevel() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPressureLevel,
          [],
        ),
        returnValue: _i7.MemoryPressureAlertLevel.info,
      ) as _i7.MemoryPressureAlertLevel);

  @override
  Map<String, dynamic> getMonitoringStats() => (super.noSuchMethod(
        Invocation.method(
          #getMonitoringStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [HybridDataParser].
///
/// See the documentation for Mockito's code generation for more information.
class MockHybridDataParser extends _i1.Mock implements _i8.HybridDataParser {
  MockHybridDataParser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void configure(_i8.HybridDataParserConfig? config) => super.noSuchMethod(
        Invocation.method(
          #configure,
          [config],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<List<_i8.FundDataItem>> parseFundData(dynamic rawData) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseFundData,
          [rawData],
        ),
        returnValue:
            _i12.Future<List<_i8.FundDataItem>>.value(<_i8.FundDataItem>[]),
      ) as _i12.Future<List<_i8.FundDataItem>>);

  @override
  _i12.Future<List<List<_i8.FundDataItem>>> parseBatchData(
          List<dynamic>? rawDataList) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseBatchData,
          [rawDataList],
        ),
        returnValue: _i12.Future<List<List<_i8.FundDataItem>>>.value(
            <List<_i8.FundDataItem>>[]),
      ) as _i12.Future<List<List<_i8.FundDataItem>>>);

  @override
  _i12.Future<List<_i8.FundDataItem>> parseAsync(dynamic rawData) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseAsync,
          [rawData],
        ),
        returnValue:
            _i12.Future<List<_i8.FundDataItem>>.value(<_i8.FundDataItem>[]),
      ) as _i12.Future<List<_i8.FundDataItem>>);

  @override
  Map<String, dynamic> getPerformanceStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getPerformanceStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i12.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [SmartBatchProcessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSmartBatchProcessor<T> extends _i1.Mock
    implements _i9.SmartBatchProcessor<T> {
  MockSmartBatchProcessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.BatchProcessingState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _i9.BatchProcessingState.idle,
      ) as _i9.BatchProcessingState);

  @override
  int get currentBatchSize => (super.noSuchMethod(
        Invocation.getter(#currentBatchSize),
        returnValue: 0,
      ) as int);

  @override
  int get queueLength => (super.noSuchMethod(
        Invocation.getter(#queueLength),
        returnValue: 0,
      ) as int);

  @override
  _i9.BatchProcessingMetrics get metrics => (super.noSuchMethod(
        Invocation.getter(#metrics),
        returnValue: _FakeBatchProcessingMetrics_13(
          this,
          Invocation.getter(#metrics),
        ),
      ) as _i9.BatchProcessingMetrics);

  @override
  bool get isIdle => (super.noSuchMethod(
        Invocation.getter(#isIdle),
        returnValue: false,
      ) as bool);

  @override
  bool get isProcessing => (super.noSuchMethod(
        Invocation.getter(#isProcessing),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  String addBatchTask({
    required List<T>? items,
    required _i12.Future<void> Function(List<T>)? processor,
    int? priority = 0,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBatchTask,
          [],
          {
            #items: items,
            #processor: processor,
            #priority: priority,
            #timeout: timeout,
          },
        ),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #addBatchTask,
            [],
            {
              #items: items,
              #processor: processor,
              #priority: priority,
              #timeout: timeout,
            },
          ),
        ),
      ) as String);

  @override
  void pause() => super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resume() => super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearQueue() => super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addStateChangeListener(
          void Function(_i9.BatchProcessingState)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addStateChangeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeStateChangeListener(
          void Function(_i9.BatchProcessingState)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeStateChangeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addMetricsUpdateListener(
          void Function(_i9.BatchProcessingMetrics)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addMetricsUpdateListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeMetricsUpdateListener(
          void Function(_i9.BatchProcessingMetrics)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeMetricsUpdateListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addErrorListener(
          void Function(
            String,
            dynamic,
          )? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addErrorListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeErrorListener(
          void Function(
            String,
            dynamic,
          )? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeErrorListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getPerformanceSummary() => (super.noSuchMethod(
        Invocation.method(
          #getPerformanceSummary,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i12.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [AdaptiveCompressionStrategy].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdaptiveCompressionStrategy extends _i1.Mock
    implements _i10.AdaptiveCompressionStrategy {
  MockAdaptiveCompressionStrategy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i10.CompressionResult> compress(dynamic data) =>
      (super.noSuchMethod(
        Invocation.method(
          #compress,
          [data],
        ),
        returnValue:
            _i12.Future<_i10.CompressionResult>.value(_FakeCompressionResult_14(
          this,
          Invocation.method(
            #compress,
            [data],
          ),
        )),
      ) as _i12.Future<_i10.CompressionResult>);

  @override
  Map<String, dynamic> getCompressionStats() => (super.noSuchMethod(
        Invocation.method(
          #getCompressionStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
