// Mocks generated by Mockito 5.4.4 from annotations
// in jisu_fund_analyzer/test/unit/core/state/global_state_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:jisu_fund_analyzer/src/core/state/feature_toggle_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFeatureToggleConfig_0 extends _i1.SmartFake
    implements _i2.FeatureToggleConfig {
  _FakeFeatureToggleConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrationProgress_1 extends _i1.SmartFake
    implements _i2.MigrationProgress {
  _FakeMigrationProgress_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FeatureToggleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeatureToggleService extends _i1.Mock
    implements _i2.FeatureToggleService {
  MockFeatureToggleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FeatureToggleConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeFeatureToggleConfig_0(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.FeatureToggleConfig);

  @override
  bool useBlocMode(String? moduleName) => (super.noSuchMethod(
        Invocation.method(
          #useBlocMode,
          [moduleName],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool useCubitMode(String? moduleName) => (super.noSuchMethod(
        Invocation.method(
          #useCubitMode,
          [moduleName],
        ),
        returnValue: false,
      ) as bool);

  @override
  void toggleModule(
    String? moduleName,
    bool? enableBloc,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #toggleModule,
          [
            moduleName,
            enableBloc,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void switchMode(_i2.StateManagementMode? mode) => super.noSuchMethod(
        Invocation.method(
          #switchMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void enableBlocForModule(String? moduleName) => super.noSuchMethod(
        Invocation.method(
          #enableBlocForModule,
          [moduleName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disableBlocForModule(String? moduleName) => super.noSuchMethod(
        Invocation.method(
          #disableBlocForModule,
          [moduleName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void enableBatch(int? batchIndex) => super.noSuchMethod(
        Invocation.method(
          #enableBatch,
          [batchIndex],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.MigrationProgress getMigrationProgress() => (super.noSuchMethod(
        Invocation.method(
          #getMigrationProgress,
          [],
        ),
        returnValue: _FakeMigrationProgress_1(
          this,
          Invocation.method(
            #getMigrationProgress,
            [],
          ),
        ),
      ) as _i2.MigrationProgress);

  @override
  void resetToDefault() => super.noSuchMethod(
        Invocation.method(
          #resetToDefault,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadFromJson(Map<String, dynamic>? json) => super.noSuchMethod(
        Invocation.method(
          #loadFromJson,
          [json],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> exportToJson() => (super.noSuchMethod(
        Invocation.method(
          #exportToJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void printCurrentState() => super.noSuchMethod(
        Invocation.method(
          #printCurrentState,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
